### ISSUE TITLE
Feature request: ACDGen command line interface

### ISSUE THREAD

**Issue by jacobjennings** [Alecrim/AlecrimCoreData#101]
This would be useful for CI validations, and would allow flexibility for a build phase or dedicated target in Xcode

**Comment by gfpacheco** [comment]
+1

**Comment by adamszeptycki** [comment]
+1

**Comment by paweljankowski** [comment]
+1

**Comment by rlbjr8898** [comment]
+1

**Comment by rlbjr8898** [comment]
I actually was able to write it.  I used another GitHub library. I was also able to add it to xcode and have it autogenerate the files each time.

**Comment by vmartinelli** [comment]
@rlbjr8898: Why you did not share this with us? ;-)

**All others**: Please check the **ACDGen** `bin` folder on `develop` branch. It would be nice if you can test if the command line tool is working properly and submit your PRs to the source code if needed. Also please leave your feedback here.

**Comment by rlbjr8898** [comment]
my apologies... inexperienced GitHub user... I should have asked for help.

**Comment by vmartinelli** [comment]
@rlbjr8898 No problem. If you have any suggestions to improve the command line tool or the **AlecrimCoreData** at all, please let us know. :-)
