### ISSUE TITLE
NSStringFromClass does not match entity class, crash

### ISSUE THREAD

**Issue by jacobjennings** [Alecrim/AlecrimCoreData#102]
from Table.swift

        let managedObjectClassName = NSStringFromClass(T.self)

            entityDescription = managedObjectModel.entities.filter({ $0.managedObjectClassName == managedObjectClassName }).first!

managedObjectClassName in this case is prepending the package name to the class, so it is Package.MyClassName while the entity class name is simply MyClassName.

**Comment by jacobjennings** [comment]
Update: http://stackoverflow.com/questions/26613971/coredata-warning-unable-to-load-class-named
Looks like you must now specify MyAppName.MyManagedObject in the core data editor under "Class" for the entity in Xcode 7

**Comment by jacobjennings** [comment]
Probably would be a helpful addition to readme to explain this new quirk

**Comment by jacobjennings** [comment]
Interesting answer in that SO: 

"When using Xcode 7 and purely Swift, I actually had to remove @objc(MyClass) from my auto-generated NSManagedObject subclass"

**Comment by vmartinelli** [comment]
I think this issue was solved by PR #107. Please let me know if the problem persists.

**Comment by waltermvp** [comment]
Im still experiencing this issue after applying the "Current Product Module" to all model classes. Am i missing something?

**Comment by waltermvp** [comment]
Also did a test by returning a String literal of the class name and xcode still crashes, will attempt with previous version of Xcode 7.2.1

**Comment by waltermvp** [comment]
OK downgraded to 7.2.1 (so it would not crash) and was able to breakpoint right after
```swift
        let managedObjectClassName = NSStringFromClass(T.self)
```

 and realized that the line that crashes is 
```swift
        let cacheKey = Duplet(managedObjectClassName, dataContext)
```

**Comment by waltermvp** [comment]
After fiddling with breakpoints the debugger got to this line"

```swift
            entityDescription = managedObjectModel.entities.filter({ $0.managedObjectClassName == managedObjectClassName }).first!
```
with
`fatal error: unexpectedly found nil while unwrapping an Optional value`

**Comment by waltermvp** [comment]
@vmartinelli any ideas? I double checked my model and both class and name are correct

**Comment by waltermvp** [comment]
Ok so I figured out an issue I was experiencing regarding this topic. I had a model file created years ago and then I added a new entity. Apparently there are inconsistencies in the way the model file creates the `managedObjectClassName` so basically, for now I have the new class Module value set to `Current Product Module` and the older entities set to none.
