### ISSUE TITLE
Saving two child context on different thread at the same time with the same parent context crash.

### ISSUE THREAD

**Issue by xrolfex** [Alecrim/AlecrimCoreData#103]
I am currently trying to save two child context on different threads at the same time. They have the same parent context and a crash occurs, so my best guess as to what is happening is the merge notification from one thread is sent up to the parent and the second one is then sent. The error message given when this occurs is that the NSSet is being mutated while enumerating. Any thoughts?

**Comment by xrolfex** [comment]
Update: I was looking through the data context code and on line 264 of DataContext.swift where the observers are added for the notifications for context merges. It currently uses ```self.performBlock```, I changed it to ```self.performBlockAndWait``` and it seems to have fixed the issue. That section of code enumerates through the changes for the merge so it seems to make sense to wait for a save to finish and queue up the next set.

**Comment by vmartinelli** [comment]
Hello. I think you found the problem. Can you make a Pull Request with this change to branch develop?

Another thing I would ask you: using the framework in day-to-day, how stable you think it is?

**Comment by xrolfex** [comment]
@vmartinelli I will create a pull request once I verify with the author that this makes sense since it is such a simple change but the underlying change is significant on threading.

**Comment by xrolfex** [comment]
@vmartinelli I can make a pull request I will do that this afternoon. As for another thing I am using the framework in a day-to-day. It is very stable other then this issue i have been fighting with. There are some places that I'm not sure why firstOrCreate does not work in a few places but that could be how the code is implemented in my part. To give you an idea the project that I'm using is 70K to 150K record initial sync and then delta updates. As well as constant background updates. I am very impressed in the core data multi context handling. The only real issue that I have taken the time to investigate is this current issue.

**Comment by vmartinelli** [comment]
Thank you for the feedback. Your PR was merged. If you have any further question or find any other bugs, please let me know.
