### ISSUE TITLE
NSInvalidArgumentException', reason: 'Unacceptable type of value for to-one relationship ... desired type = Towns; given type = Towns

### ISSUE THREAD

**Issue by thieu75** [Alecrim/AlecrimCoreData#106]
Hello there,

So, I'm scratching my head since few hours and I can't understand this.

So, I have 2 entities in my core data model:

> Towns
> Restaurant

I have defined the relationship one to many and inverse.
(yep, you've got it, a Town can have multiple restaurants ;))

I'm using the CoreData Stack to persist elements from CloudKit. 
In a class that grab content from ClouKit, I create the context:

```
let dataContext = DataContext()
```

Then I have a bunch of functions that call class functions that create if needed the NSManagedObjects

```
let town = Towns.createTownsFromCK(record, dataContext: self.dataContext) ...
let restaurant = Restaurants.createRestaurantFromCK(record, dataContext: self.dataContext) ...
```

As you can see I transmit the dataContext. So it's the same for Restaurants and Towns.
CloudKit restaurant objects are grabbed after Towns have been locally saved.

```
do {
     try dataContext.save()
} catch {

}

let restaurantPredicate = NSPredicate(format: "town == %@", record.recordID)
let restaurantQuery = CKQuery(recordType: "Restaurants", predicate: restaurantPredicate)
self.publicDB.addOperation(createQueryOperation(restaurantQuery, cursor: nil, resultblock:fetchedRestaurantsRecord))
```

When grabbed, I can create restaurants NSManagedObject and add properties, but when I want to link the town, I have this strange error when I set the town:

```
if let cktownreference = record["town"] as? CKReference, town = dataContext.towns.filter({ $0.ckid! == cktownreference.recordID.recordName }).first {
        restaurant.town = town
 }
```

The error (weird one...):

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for to-one relationship: property = "town"; desired type = Towns; given type = Towns; value = <Towns: 0x7ff9f8d06ff0> (entity: Towns; id: 0xd000000000080000 <x-coredata://0DEF9EB6-F096-41FE-ACDA-E19B06340183/Towns/p2> ; data: {
    ckid = "6665ca0f-af57-4305-8e18-ced7540e6279";
    name = Paris;
    recordChangeTag = ii0l38hp;
    restaurant = "<relationship fault: 0x7ff9fbb56950 'restaurant'>";
}).'
```

Here are my Model:

<img width="550" alt="capture d ecran 2015-12-14 a 19 42 55" src="https://cloud.githubusercontent.com/assets/2086457/11790226/e9852470-a29a-11e5-946d-ed4524ddb5de.png">

<img width="543" alt="capture d ecran 2015-12-14 a 19 42 45" src="https://cloud.githubusercontent.com/assets/2086457/11790235/f4d4d3de-a29a-11e5-879c-6046d47df64f.png">

1000 thanks for your help!
Do not hesitate to ask me questions if it's not clear.

Matthieu

**Comment by vmartinelli** [comment]
Hello. Reading your code I found `$0.ckid!` inside there filter closure. Did you try to remove the `!` after the property name?

**Comment by thieu75** [comment]
thanks @vmartinelli but same result with or without the `!` . I have the unwrapped town object.
Anything strange in my model ?

**Comment by thieu75** [comment]
Ok, I've just run new tests by using default Context:

```
let appDel: AppDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
let context: NSManagedObjectContext = appDel.managedObjectContext
            
let restaurant = NSEntityDescription.insertNewObjectForEntityForName("Restaurants", inManagedObjectContext: context) as! Restaurants
            
restaurant.ckid = String(record.recordID.recordName)
restaurant.recordChangeTag = record.recordChangeTag
...
           
let townFetch = NSFetchRequest(entityName: "Towns")
do {
          let fetchedTowns = try context.executeFetchRequest(townFetch) as! [Towns]
          if let cktownreference = record["town"] as? CKReference {
               for town in fetchedTowns {
                        if town.ckid == cktownreference.recordID.recordName {
                            restaurant.town = town
                        }
                    }
                }               
            } catch {
                fatalError("Failed to fetch Towns: \(error)")
            }

           do {
                try context.save()
            } catch {
                fatalError("Failure to save context: \(error)")
            }
```

Just a test, I'll use predicate after ;)

BUT it works. I can create, fetch then save without problems. The `restaurant.town = town` does not crash anymore.

Does the problem came from the framework or the way I use it ? passing the context from a class to the NSManagedObject Class ? No idea. And you ?!

**Comment by abbeycode** [comment]
@thieu75 I'm not clear on what you changed that made a difference. I'm hitting the same problem now and would like to know how to solve it.

**Comment by thieu75** [comment]
@abbeycode Sorry i wasn't clear. I'd just have use plain old coredata approach by removing the Context() and so on...

**Comment by thieu75** [comment]
Correction : by removing the DataContext()...

**Comment by vmartinelli** [comment]
There has been some progress in this regard?

**Comment by thieu75** [comment]
Nope, not on my part, sorry
