### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by bzdybowicz-Altimi** [Alecrim/AlecrimCoreData#109]
Hello,

I did not go deeper into the issue, but my app started to freeze regularly when I updated to version 4.0.3 from 4.0-beta.1. The issue is so easy to reproduce that I had to immediately downgrade.  This may be a problem with synchronous calls to main thread although I have no idea since there is neither log nor crash one problem appears.

Looking forward for answers, more information,
Cheers,
BZ

**Comment by bevbomb** [comment]
I've been experiencing the same issues when looping through arrays to map data
