### ISSUE TITLE
Could Not Build Objective-C Module 'AlecrimCoreData'

### ISSUE THREAD

**Issue by izad** [Alecrim/AlecrimCoreData#11]
I keep getting this error when trying to import AlecrimCoreData framework. Any idea what went wrong? I am fairly to to iOS development so it is more than likely I screwed up the installation somehow. I think a more detailed installation instruction would benefit beginners like me.

**Comment by JanRuettinger** [comment]
same here.
Could you implement pod install?

**Comment by vmartinelli** [comment]
CocoaPods is now supported in version 2.1. Can you test to see if it works correctly?
