### ISSUE TITLE
cannot hold instances of entity (<NSEntityDescription: >) name 

### ISSUE THREAD

**Issue by Rustemt** [Alecrim/AlecrimCoreData#110]
Hi , I got a error when I save the entity cannot hold instances of entity (<NSEntityDescription: >) name

**Comment by vmartinelli** [comment]
Hello. Can you test if the error occurs using the version from `develop` too?

**Comment by Rustemt** [comment]
Thanks , I solve it

**Comment by vmartinelli** [comment]
OK. Let me know if the problem persists. I’ll close the issue.
