### ISSUE TITLE
Use String instead of NSString even when not using scalar properties

### ISSUE THREAD

**Issue by gfpacheco** [Alecrim/AlecrimCoreData#113]
Xcode's "Create NSManagedObject subclass" command already uses `String` instead of `NSString`.

These are the properties generated by Xcode and ACDGen (both not using scalar properties):

Xcode:

    @NSManaged var name: String?
    @NSManaged var remoteID: NSNumber?

ACDGen:

    @NSManaged var name: NSString?
    @NSManaged var remoteID: NSNumber?

**Comment by vmartinelli** [comment]
Hello. Glad you brought that up. It's been so long since I used Xcode generator that I do not know how are the latest versions. Do you know if other types are changed too? Is there any documentation for it?

Well... And the last question: it would be good to change the **ACDGen** to use scalar properties in some cases even if the option to not use them was specified or `String` should be even considered non-scalar?

**Comment by gfpacheco** [comment]
Hi, I just tested Xcode tool again, to see what would come out.

These are the generated properties for an entity with all types of attributes:


    @NSManaged var integer16: NSNumber?
    @NSManaged var integer32: NSNumber?
    @NSManaged var integer64: NSNumber?
    @NSManaged var decimal: NSDecimalNumber?
    @NSManaged var double: NSNumber?
    @NSManaged var float: NSNumber?
    @NSManaged var string: String?
    @NSManaged var boolean: NSNumber?
    @NSManaged var date: NSDate?
    @NSManaged var binaryData: NSData?
    @NSManaged var transformable: NSObject?

**Comment by vmartinelli** [comment]
Thank you very much! :-)

So... They only replaced `NSString` with `String`. Do you think it is really worth to change **ACDGen** as well?

**Comment by gfpacheco** [comment]
I just added Alecrim to my project and I'm making some changes to the db scheme. But, because my project expects a `String` field, every time I run **ACDGen** I have to replace `NSString` with `String` in all generated files.

Answering your question: **for me** would be very helpful if you could change it :stuck_out_tongue:

**Comment by vmartinelli** [comment]
Maybe we can put another option on **ACDgen** to handle this, something like "Always use Swift.String for string types” below the “Use scalar properties...” checkbox and handling it in code generation? If so a PR about this will be very much appreciated.
