### ISSUE TITLE
Duplicate NSManagedObject in single context?

### ISSUE THREAD

**Issue by sobri909** [Alecrim/AlecrimCoreData#114]
I'm getting a strange bug. Anyway, let me explain.

I use a single `DataContext` for all creation, deletion, fetching, and saving. It's provided by a singleton. I do all Core Data actions on the main thread. 

My app is long running (24/7, most often in the background), and everything works fine. I create objects, save, modify, save, fetch, etc.

Then maybe after one day iOS will decide to kill my app (for memory reasons - I have some more memory optimising to do). That's fine. The app should come back again and continue where it left off. But something strange happens... 

One of the objects will come back from a fetch in a very old state. Even though in the past day it has been updated and saved many times and has come back from fetches with correct details every time, this time it will come back in an old state. Not the same state as when it was created, but maybe the state it had after being saved 2 or 3 times.

I believe what is happening is there are two instances of the one NSManagedObject. At some time soon after the object is first created a second copy of it appears, and that second copy is the one that has all subsequent changes and saves made to it. But then when the app is relaunched (after iOS killed it), the second copy disappears and the first copy is resurrected. 

I have confirmation that there are two copies of the object, because I am lazy saving them to a remote server, and recording their Core Data primary keys. 

Here are the server side objects:

<img width="625" alt="screen shot 2016-02-05 at 5 feb 14 59 57" src="https://cloud.githubusercontent.com/assets/1203835/12840833/345ced3c-cc19-11e5-8be8-8ccf4ee4cd00.png">

As you can see, they both have the same Core Data primary key, but one of them is only 1 minute duration and the other has the correct almost 2 hour duration. But after the app relaunch, the correct one disappears from Core Data and only the old, incorrect object continues to exist. 

This is happening every day, on maybe one or two objects. But I can't see a proper pattern yet. I don't have any good guesses :(

**Comment by sobri909** [comment]
Okay, I caught it in action again today. 

This time I took a download of the app's container before relaunching the app, then another after relaunching the app. 

Curiously, the sqlite file *before* relaunching also showed the incorrect data, but the app itself was getting the correct data from queries. So it looks to me like the child context hadn't propagated its saves upstream to the root saving context, thus the changes never made it to the sqlite file.

One far fetched guess is that the call to `save()` is sometimes going directly to the superclass method instead of the subclass method. Though that sounds like nonsense. But it would at least explain why the save wasn't propagated upstream to the root saving context. 

@vmartinelli any ideas? I'm open to any wild guesses at this point, because it's not making much sense.

**Comment by vmartinelli** [comment]
Hello.

Well... This appears to be more related to Core Data itself than **AlecrimCoreData**. There is an intricate mechanism related to managed object contexts and managed objects , how and how long they “live” in Core Data implementation. You can say if objects are weak or strong, when to have faults and so on... I recommend to research more about this topics in the docs.

I know that Core Data is full of mysteries. I’m always trying to unveil and understand them better to provide a better version of **ACD**. Please tell me if you have any progress with this and keep reporting here as you did, so other **ACD** users and me can help and/or help too.

Regards.

**Comment by sobri909** [comment]
Yeah, after having a fairly solid look through the AlecrimCoreData source I haven't been able to spot anything that seems like it could cause it. And I've eliminated all the obvious and non obvious potential causes from my own code. So it looks like it could be me misunderstanding of how Core Data works. Though I'm failing to see where.

Today's experiment is to add liberal use of `refreshObject()` before important object updates and saves. We'll see if that has any effect...

**Comment by sobri909** [comment]
One debugging approach I had wanted to try, but that looks to be impossible with the current structure of AlecrimCoreData, is to use the root saving context directly, instead of a child context. It's not the structure I *want* to use, but it would help to eliminate some more possibilities of what's going wrong.

**Comment by sobri909** [comment]
I still haven't been able to find the cause of this, but I've reduced the chances of it happening in my app enough that it's no longer a concern, so I'm going to close the task.

I'm still convinced something fishy is going on (I can still catch it in the act, on occasion), but yeah, it almost certainly is at the Core Data level rather than AlecrimCoreData. Someday I'll find it...
