### ISSUE TITLE
Using firstOrCreated() without predicate set

### ISSUE THREAD

**Issue by alexth** [Alecrim/AlecrimCoreData#116]
Is it possible to use firstOrCreated() without predicate? 
I need to have the only one Entity of a kind in the all app lifecycle. So, if no one exist - create one, if it already exist - fetch it to me.
Can I user firstOrCreated() for this?

Best regards,
Alex

**Comment by vmartinelli** [comment]
Hello. I think you can use something like:

```swift
let entity = dataContext.entities.first() ?? dataContext.entities.createEntity()
```

Please let me know if this solved your issue.

**Comment by alexth** [comment]
This is really elegant!
Thank you @vmartinelli.
Have a good day!

**Comment by vmartinelli** [comment]
Yay! :-)
