### ISSUE TITLE
Filter with option string property

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#117]
`let foundUser = context.users.firstOrCreated { $0.userId == expectedUserId }`

Getting build error:

`Binary operator '==' cannot be applied to operands of type 'NullableAttribute<NSString>' and 'String'`

**Comment by AnthonyMDev** [comment]
`let foundUser = context.users.firstOrCreated { $0.userId.isEqualTo(expectedUserId) }`

works just fine.

So it seems like the operator overloaded for the `==` operator that covers this case was just not implemented.

**Comment by vmartinelli** [comment]
Hello. Perhaps this is somehow related to #113?

**Comment by vmartinelli** [comment]
It appears that Xcode now generates string properties as `String` instead of `NSString` even if you do not want to use scalar types. Maybe some `String` to `NSString` and `NSString` to `String` bridging has changing in recent versions of Swift?

**Comment by vmartinelli** [comment]
Please verify if the new **ACDGen** option to generate `String` type instead of `NSString` solves this. Thank you.

**Comment by AnthonyMDev** [comment]
Thanks, but I ended up changing 'String' to 'NSString' manually in my *ACDGen* generated files last week, and it still didn't seem to be working as expected.

**Comment by waltermvp** [comment]
Same issue here. Tried regenerating with ACDGen to NSString and issue still persisted.
