### ISSUE TITLE
Explicit unwrap of managedObjectContext

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#118]
In `NSManagedObjectExtensions`, I feel like it is a bad idea to explicitly unwrap the `managedObjectContext` on the `delete()` and `refresh(mergeChanges:)` methods. Maybe we should  mark these with `throw` and throw an error, but crashing the application on a `nil` `managedObjectContext` seems unsafe.

````
extension NSManagedObject {
    
    public func delete() {
        self.managedObjectContext!.deleteObject(self)
    }
    
    public func refresh(mergeChanges: Bool = true) {
        self.managedObjectContext!.refreshObject(self, mergeChanges: mergeChanges)
    }

}
````

**Comment by vmartinelli** [comment]
I'll close this issue as the PR was merged. Thank you.
