### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by Urkman** [Alecrim/AlecrimCoreData#12]
please add Support for cocoapods

**Comment by tomco** [comment]
Any reason why this issue is closed? CocoaPods now supports Swift. But Alecrim Core Data is not yet listed [cocoapods.org](http://cocoapods.org/?q=AlecrimCoreData). Could you please make this project available via CocoaPods.

**Comment by vmartinelli** [comment]
CocoaPods is now supported in version 2.1. Can you test to see if it works correctly?

**Comment by Urkman** [comment]
Why the target is iOS 8.2?
Shouldn't iOS 8.0 be OK?

**Comment by vmartinelli** [comment]
I did not test the framework on iOS 8.0, but I think your are right.

Do you think new a version 2.1.1 should be released only for this change? Or most of the developers are already using as target at least version 8.2 of iOS?

**Comment by Urkman** [comment]
So, for me I'm targeting iOS 8.0 for my Apps...

**Comment by vmartinelli** [comment]
Updated in the last prerelease. Thank you.
