### ISSUE TITLE
Cannot initialise DataContext()

### ISSUE THREAD

**Issue by DesmondPang** [Alecrim/AlecrimCoreData#121]
It could not initialise DataContext object by using let dataContext =  DataContext().

It gave the error fatal error: Unhandled error. See callstack.: file /Users/..../Pods/AlecrimCoreData/Source/AlecrimCoreData/Core/Enums/AlecrimCoreDataError.swift, line 33

I cannot debug.

**Comment by DesmondPang** [comment]
I found the problem that is about the space in the app name. [https://github.com/Alecrim/AlecrimCoreData/issues/95](url)

I change the App Name into App_Name. It is fine. However, I would like to keep the space for my app name. How to fix it?

**Comment by DesmondPang** [comment]
Finally, I found the solution. I hope you can remind this issues in README.md

var dataContext = DataContext(dataContextOptions: try! DataContextOptions(managedObjectModelURL: NSBundle.mainBundle().URLForResource("App_Name", withExtension: "momd")!))

**Comment by vmartinelli** [comment]
Please verify if the last version (4.1.1) solves this problem. Thank you.

**Comment by lluisgerard** [comment]
Just a heads up: 
I moved to `develop` branch today because I had an unrelated issue with `FetchedResultsController`.
This error came out, and I solved it by using the solution provided in the comment https://github.com/Alecrim/AlecrimCoreData/issues/121#issuecomment-183898516
