### ISSUE TITLE
10.9 Support?

### ISSUE THREAD

**Issue by ghan0018** [Alecrim/AlecrimCoreData#122]
Hi Alecrim,

I love your pod.  Thanks for your work.  Do you plan on supporting 10.9 still?  The readme says yes, but the podspec says no.  Also, it seems that specifying "4.0" of your pod does not work with cocoapods - is it improperly tagged perhaps?

**Comment by vmartinelli** [comment]
Hello. Please give the version 4.1.1 a try. The target version for OS X is now 10.9 again.
