### ISSUE TITLE
ReactKit Integration

### ISSUE THREAD

**Issue by bevbomb** [Alecrim/AlecrimCoreData#123]
In the last I've used ReactKit to watch for changes in entities which has worked great for everything except arrays and sets, but after migrating from the old version of SugarRecord to this framework, none of my streams seem to work.
I don't know if this is something to do with the way that I'm mapping the entity to update it or if it's something to do with the threads that the context works on but I'm stumped! 
I even went as far as created non NSManaged variables and adding the same data to those, the stream works inside the entity but never makes it out

**Comment by vmartinelli** [comment]
Well... Some ReactKit expert can help us? ;-)

**Comment by vmartinelli** [comment]
I’ll close this issue for now. If you have further questions, please reopen it.
