### ISSUE TITLE
Deadlock when bulk creating entities

### ISSUE THREAD

**Issue by bevbomb** [Alecrim/AlecrimCoreData#125]
I'm getting a terrible deadlock when i loop through an array and use firstOrCreated to create entities then map them with a function after

**Comment by vmartinelli** [comment]
Hello. Are you saving the context at the end when all the entities are already created or the context is being saved after each entity is created?

**Comment by bevbomb** [comment]
Say a have a Post entity, i create the post entity with its initial data, i save the context, then i being creating all of the Comments and adding them to the post, after the all of the items are created and added to Post as a relationship, i save the context again.

**Comment by vmartinelli** [comment]
There is some special need to save the context at first time or the Post entity can be created, all the data and relationships filled, and then saved all together using only one save call?

**Comment by vmartinelli** [comment]
I’ll close this issue for now. If you have further questions, please reopen it.
