### ISSUE TITLE
Filter & OrderBy sample code doesn't compile

### ISSUE THREAD

**Issue by alvinmeimoun** [Alecrim/AlecrimCoreData#129]
Trying to implement the README.md sample code doesn't compile

`let filteredSections = DataContext().sections.filter { $0.isInMenu == true }.orderBy { $0.displayOrder }`

> Value of type '[SectionEntity]' has no member 'orderBy'

XCode 7.3

**Comment by vmartinelli** [comment]
Hello. If the code in your app is the same from here, I think you may have to put the `.filter` and the `.orderBy` each one in its own line or rewrite to use parentheses at least in `filter`. Swift trailing closure syntax things... ;-)

**Comment by alvinmeimoun** [comment]
Hello, i put each on its own line and used parentheses, problem still persist

`let filteredSections = DataContext().sections`
`.filter({ $0.isInMenu == true })`
`.orderBy({ $0.displayOrder })`


And my DataContextExtension.swift
`extension DataContext {`
`    var sections:      Table<SectionEntity>     { return Table<SectionEntity>(dataContext: self) }`
`}`

**Comment by alvinmeimoun** [comment]
Solved, i generated my entities with XCode generator instead of ACDGen
