### ISSUE TITLE
Crash on 'mergeChangesFromContextDidSaveNotification(_:)'

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#131]
I'm periodically (about 3% of the time) getting crash reports on `mergeChangesFromContextDidSaveNotification(_:)`

I'm not sure if this is a user error on my part, but the crash is occurring in the closure from `addObservers()` on `ChildDataContext`, so I figured I'd post this here to get help investigating if this a problem in `Alecrim`.

Sometimes I'm getting `EXC_BAD_ACCESS KERN_INVALID_ADDRESS`, and sometimes I'm getting `[__NSCFSet addObject:]: attempt to insert nil`

```
Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x180995b90 objc_msgSend + 16
1  CoreData                       0x1831c7538 -[NSManagedObjectContext(_NSInternalAdditions) _refaultObject:globalID:boolean:] + 116
2  CoreData                       0x18321b168 -[NSManagedObjectContext _mergeRefreshObject:mergeChanges:withPersistentSnapshot:] + 480
3  CoreData                       0x18321c5fc -[NSManagedObjectContext _mergeChangesFromDidSaveDictionary:usingObjectIDs:] + 2280
4  CoreData                       0x18321cc20 -[NSManagedObjectContext mergeChangesFromContextDidSaveNotification:] + 500
5  AlecrimCoreData                0x100e47df4 ChildDataContext.(addObservers(ChildDataContext) -> () -> ()).(closure #1).(closure #1) (DataContext.swift:273)
6  CoreData                       0x18321d08c developerSubmittedBlockToNSManagedObjectContextPerform + 196
7  libdispatch.dylib              0x180d6947c _dispatch_client_callout + 16
8  libdispatch.dylib              0x180d6eb84 _dispatch_main_queue_callback_4CF + 1844
9  CoreFoundation                 0x1812d4dd8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
10 CoreFoundation                 0x1812d2c40 __CFRunLoopRun + 1628
11 CoreFoundation                 0x1811fcd10 CFRunLoopRunSpecific + 384
12 GraphicsServices               0x182ae4088 GSEventRunModal + 180
13 UIKit                          0x1864d1f70 UIApplicationMain + 204
14 MyApp                          0x1000f2ad8 main (AppDelegate.swift:33)
15 libdispatch.dylib              0x180d9a8b8 (Missing)
```

Possibly related: http://stackoverflow.com/questions/27953692/exc-bad-access-on-mergechangesfromcontextdidsavenotification

**Comment by AnthonyMDev** [comment]
I've made an attempted fix by ensuring that I'm never trying to do multiple transactions to the database at the same time in my code base. I can't guarantee that this fixes it, as this bug is sporadic and difficult to reproduce.

We may want to consider adding some safety features to this library that ensure that two saves will not be called simultaneously from different threads internally.

**Comment by glebus** [comment]
Hi, @AnthonyMDev! Do you have any update about this issue?)
