### ISSUE TITLE
To many relationship

### ISSUE THREAD

**Issue by adamszeptycki** [Alecrim/AlecrimCoreData#132]
Hey,
Could someone provide example how to use any().

Lets say I have collections with many albums. And I would like to get collections at least album with name longer then 5 characters.

**Comment by amayatsky** [comment]
```any()``` is just a shortcut for ```collections.count > 0```.
What you need is a ```filter()```: ```collections.filter({e in e.album.characters.count > 5})```

**Comment by vmartinelli** [comment]
I’ll close this issue for now. If you have further questions, pleas reopen it.
