### ISSUE TITLE
Notification for DidMergeChangesFromRootContext

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#137]
I'd like to have a notification that I can observe on a context after the context merged changes from a save on the root context. I don't want to use the `NSManagedObjectContextObjectsDidChangeNotification` because I'm only concerned about changes that are being merged from the root context, not local changes.

Would it be appropriate for this feature to be integrated into `AlecrimCoreData`? I'd like to add the behavior to `ChildDataContext`. 

I will make a PR if you are interested.

**Comment by vmartinelli** [comment]
Hi. It would be nice to handle the opposite situation too. Can you explain in more details how its implementation would be?

**Comment by AnthonyMDev** [comment]
Not sure what you mean. What is the opposite situation?

I would just add a notification to be posted from `ChildDataContext` when we merge saved changes from the root context.
