### ISSUE TITLE
Pull FetchRequestController out into a separate pod.

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#138]
I'd like for `FetchRequestController` and `FetchRequestControllerDelegate` to be moved into a separate pod.

This is a really useful abstraction of `NSFetchedResultsController` into Swift with generics, and I think people should be able to use it without depending on the entire `AlecrimCoreData` pod.

I'm interested in creating a generic subclass of `FetchRequestController` that allows you to map your `NSManagedObjects` into other objects to better support dependency inversion for view controllers. I think this subclass would be a perfect fit for a new `FetchRequestController` pod, but it doesn't make sense for this all to be packaged tightly with `AlecrimCoreData`.

Thoughts?

**Comment by vmartinelli** [comment]
Hello. I think that FetchRequestController related features are very suitable to be moved to other project (pod or SPM package) but I do not know if this will be possible to be done in the next release. I’m working to add “independente data sources” support (with them one Table/Collection view will be able to have several bound fetch request controllers, each of them handling their own index paths and cells). This is other set of features that would be nice to be in other project with **ACD** as dependency.

**Comment by AnthonyMDev** [comment]
I don't see why this can't be pulled out for the next release. It shouldn't take long to create a new pod with these features in it and a dependency on ACD. Is there any reason why the next release would require these features to be included?
