### ISSUE TITLE
Crash when accessing to a table after entity regeneration

### ISSUE THREAD

**Issue by alvinmeimoun** [Alecrim/AlecrimCoreData#139]
Hi,

I added some fields to my datamodel, regenerated entities with ACDGen and deleted app from simulator.
Now when i'm trying to access to a table `DataContext().sections` (tryed with a fresh installed app after simulator reset and placed this line after viewDidLoad), i got a crash `EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`. 

This crash appears in file **Table.swift** at **line 42** `entityDescription = managedObjectModel.entities.filter({ $0.managedObjectClassName == managedObjectClassName }).first!`

Is it a bug or i missed something ?

Thanks

**Comment by m1entus** [comment]
Hi i had same issue, this is a problem with XCode and generated content of xcdatamodel, XCode generate managedObjectClassName this way ".SomeClass" insted of "SomeClass" or "Module.SomeClass". Not sure if they fixed it in newest version..

**Comment by alvinmeimoun** [comment]
Thanks @m1entus  , we need to specify all entities to the current product module , [this solution](http://stackoverflow.com/questions/25076276/unable-to-find-specific-subclass-of-nsmanagedobject) solved the problem
