### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by Tom29** [Alecrim/AlecrimCoreData#14]
I already drag AlecrimCoreData.xcodeproj to my project.
Add framework and import AlecrimCoreData.
Already had coredata file: CoreData.xcdatamodeld

But i could not begin with AlecrimCoreData
db.EntityName ~> no attribute after and < < error type > >

**Comment by abhim8** [comment]
would moving to cocoapods make sense for faster install and also make future updates painless?
http://nshipster.com/cocoapods/

**Comment by vmartinelli** [comment]
CocoaPods is now supported in version 2.1. Can you test to see if it works correctly?
