### ISSUE TITLE
'resetFilter()' without performing fetch on 'FetchRequestController'

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#141]
I'd like to be able to call `resetFilter()` on `FetchRequestController` without performing a fetch.

My use case is that I need to reset my filters back to the initial predicate, then add NEW filters before performing a new fetch.

**Proposal**
Add a `performFetch` parameter to the function.

`resetFilter(performFetch: Bool = false)`

Implementation would also require adding the `performFetch` parameter to `resetPredicate()`

I'd be willing to make a PR, but wanted to get feedback on the proposal first.

**Comment by vmartinelli** [comment]
It makes perfect sense. It would be nice to have a PR about this. We will need some doc/info about the changed behaviour (some users may expect the former behaviour).

**Comment by AnthonyMDev** [comment]
I'll make a PR tomorrow. It will include documentation for the changed methods.
