### ISSUE TITLE
Add options to persistent store

### ISSUE THREAD

**Issue by waltermvp** [Alecrim/AlecrimCoreData#145]
Is there a way to pass in options to the persistent store during it's initialization. I need to set `NSFileProtectionComplete` as an option for encryption.

```objectice-c
[_persistentStoreCoordinator addPersistentStoreWithType:NSSQLiteStoreType configuration:nil URL:storeURL options:@{ NSPersistentStoreFileProtectionKey : NSFileProtectionComplete } error:&error]
```

_i know the lib is for swift just found this snippet to copy paste_

**Comment by AnthonyMDev** [comment]
You can initialize your `DataContext` by passing in your own `DataContextOptions`. This `struct` can have its `persistentStoreOptions` set.

You can pass this `struct` to the `options` parameter when initializing a `ChildDataContext`.

Alternatively, you can pass these in the initialization of a `RootSavingDataContext` that you maintain a reference to and then initialize all of your `ChildDataContext`s by passing them a reference to your `RootSavingDataContext`. If you are planning on using multiple child contexts (which you should be doing for background threads), then this is the preferred method.

**Comment by waltermvp** [comment]
@AnthonyMDev got it thanks 👍
