### ISSUE TITLE
Remove 'didUpdateSection()' from 'FetchRequestController'

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#146]
'didUpdateSection()` is unneeded and should never be called. The documentation for `controller(controller: NSFetchedResultsController, didChangeSection sectionInfo: NSFetchedResultsSectionInfo, atIndex sectionIndex: Int, forChangeType type: NSFetchedResultsChangeType)` on `NSFetchedResultController` states:

> Valid values are NSFetchedResultsChangeInsert and NSFetchedResultsChangeDelete.

The `NSFetchedResultsChangeUpdate` type should only be used for item updates, not section updates.

Can I make a PR to remove this closure?

**Comment by vmartinelli** [comment]
Sure! :)
