### ISSUE TITLE
Patch version to fix memory leak

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#148]
The memory leak in #126 has become a mission critical problem for me. I know that there is a fix that has been pushed to the `develop` branch, but we are pretty far away from pushing a new version here still.

Is there any way that we can get a patch version `4.1.2` pushed to `CocoaPods` that includes just this fix merged into master? 

Having all of our contexts leaking is causing huge issues, as it means that every object retained by those contexts is also leaking. This adds up to massive amounts of memory.

Thank you.

**Comment by vmartinelli** [comment]
Hello. Sorry for delay in responding. Can you check if the last release (4.2) is working properly, including this fix?

**Comment by AnthonyMDev** [comment]
@vmartinelli Thanks for working on this. Unfortunately this new version is not working at all for me. Everything was working before but I'm getting a ton of errors that look like this:

```
"Unacceptable type of value for to-one relationship: property = "organization"; desired type = ZROrganization; given type = ZROrganization;
```

**Comment by AnthonyMDev** [comment]
@vmartinelli 
PR #149 fixes the issue. Please pull this in to a new version ASAP, as the new version has made the library completely dysfunctional for anyone using multiple PSCs.
Multiple PSCs are inevitable when you are unit testing, as the CoreData stack is torn down between each test.

Thank you!

**Comment by AnthonyMDev** [comment]
The memory leak is fixed! Thanks! I'll close these issues.
