### ISSUE TITLE
Swift 3 Version push

### ISSUE THREAD

**Issue by AnthonyMDev** [Alecrim/AlecrimCoreData#152]
Now that the Xcode8 GM seed is out, a Swift 3 version should be pushed soon.

@vmartinelli Is there anything left that needs to be completed before this version is pushed to the CocoaPods spec repo?

**Comment by AnthonyMDev** [comment]
I just pulled in the `feature/swift-3` branch as an explicit dependency for one of my projects, and I'm getting a bunch of errors for functions that are only available in iOS 10.0 or newer. The Swift 3 version of this pod isn't planning on dropping iOS 9.0 support is it?

**Comment by danfsd** [comment]
@AnthonyMDev I saw many pods (like **Alamofire**) bumping up the target deployment from `8.0` to `9.0` and I'm almost sure that the `9.0` won't be dropped on the near future.

Still there are some major API changes in **Swift 3.0** and they will not only be reflected on **AlecrimCoreData** framework, the `*.generated` class files should also be updated to the new syntax, have you done it?

**Comment by AnthonyMDev** [comment]
@danfsd Well I'm fine with 9.0, but the current Swift 3 branch is not supporting 9.0. That's why I brought it up. 

I have not updated ACDGen to Swift 3.0.

**Comment by danfsd** [comment]
I see, I just realized that too. The `AlecrimCoreData.podspec` minimum version is set to `8.0` while the code is using iOS 10.0 only stuff.

**Comment by danfsd** [comment]
@vmartinelli It would be nice to maintain the support to iOS 9.0 instead of making these breaking changes from iOS 10.0. We just need support to **Swift 3** at the moment.

What are your thoughts about this?

**Comment by vmartinelli** [comment]
Hi. Well... Lack os iOS 9 support: this is one the main reasons the **ACD** Swift 3 compatible version is still in beta. Working in Apple's Core Data using iOS 9 SDK and iOS 10 SDK are now very different things.

I'm working on the new version trying to bring the benefits of iOS 10 and to maintain compatibility with iOS 9.

**Comment by AnthonyMDev** [comment]
@vmartinelli It shouldn't be a problem if you use the `available` attributes to selectively run the code for the current iOS version. I've added these attributes and I've got the pod working with iOS 9 and 10 currently. I already made the PR to fix this #153.
