### ISSUE TITLE
Can not pod the updated version

### ISSUE THREAD

**Issue by DesmondPang** [Alecrim/AlecrimCoreData#154]
I have tried 

pod 'AlecrimCoreData'

pod 'AlecrimCoreData’, ’~>4.2.2’

pod 'AlecrimCoreData’, ’~>4.2.3’

It still get 4.2.1.

**Comment by DesmondPang** [comment]
Oh, I fixed it by using pod 'AlecrimCoreData', git: 'https://github.com/Alecrim/AlecrimCoreData.git'

**Comment by m1entus** [comment]
Can you push version 4.2.3 to cocoapods ? 👍 ?

**Comment by vmartinelli** [comment]
Hello. Since the 4.2.3 tag I'm getting an `unknown: Encountered an unknown error` from Cocoa Pods while trying to push the Swift 2.3 compatible version. I'll update to the release version of macOS Sierra and I'll try again. If someone had the same problem and find a solution, please let me know.

**Comment by m1entus** [comment]
Have you tried installing cocoapods 1.1.0 --pre ? I have issue when i was trying to push swift 3.0 code, maybe it will help ?

**Comment by vmartinelli** [comment]
cocoapods-core-1.1.0.rc.2 did the trick. Thank you very much! :)
