### ISSUE TITLE
Binding to tableView retains a strong reference to the tableView

### ISSUE THREAD

**Issue by Maxwellimus** [Alecrim/AlecrimCoreData#155]
I recently created a UITableView that used quite a bit of memory while on screen.  Which made memory shoot up quickly when navigating around.  It seemed that in the callback function for updates to the tableView it was calling beginUpdates() on the tableView that was passed in, creating a strong reference.  I made a fork of the repo to test a solution which seemed to work.  Moved the call for beginUpdates() into the .didChangeContent callback since all changes are tracked via Sets anyways.  Also, passed in tableView as weak instead of unowned.  Was there a reason it should be unowned?  Seemed like that could cause a crashing race condition if the UITableView is getting cleaned up and FetchedRequestController's callbacks happen.

Here's the changes I made that seemed like a fix to me:

https://github.com/Alecrim/AlecrimCoreData/compare/master...Maxwellimus:master

Any guidance on how to get these changes reviewed and back into the develop branch would be great.  Thanks!

**Comment by vmartinelli** [comment]
Hello.

Thank you for catching this issue. I did not have it on my projects, but the reference being `weak` instead `unowned` is a more secure approach.

I'm committing a new version fixing this issue (Swift 2.3 compatible version.)

About to get your contributions reviewed and added to **ACD** please take a time to review the instructions in this link: https://help.github.com/articles/creating-a-pull-request.

**Comment by Maxwellimus** [comment]
Hey,

Thanks for integrating the changes.  Sorry I didn't set it up as a pull request the first time.  There was one thing missing in the code integration though.  Moving the `beginUpdates` call to the weak referenced tableView.

I created a pull request here with a fix:

https://github.com/Alecrim/AlecrimCoreData/pull/156
