### ISSUE TITLE
Am getting error like this Help!!

### ISSUE THREAD

**Issue by jeffayan** [Alecrim/AlecrimCoreData#159]
![screen shot 2016-11-07 at 12 03 20 pm](https://cloud.githubusercontent.com/assets/17008251/20048413/72a15702-a4e2-11e6-900f-76fce2b55fb2.png)

**Comment by vmartinelli** [comment]
Hello. Could these errors be related to issue # 158?

**Comment by jeffayan** [comment]
yep, Issue fixed by adding 
@available(iOS 10.0, *)
@available(macOSApplicationExtension 10.12, iOSApplicationExtension 10.0, tvOSApplicationExtension 10.0, watchOSApplicationExtension 3.0, *)
