### ISSUE TITLE
Swift 3 ambigous use of 'row'

### ISSUE THREAD

**Issue by mzeeshanid** [Alecrim/AlecrimCoreData#161]
I just migrated to swift 3 and i am getting this error ambiguous use of row on indexPath same on  section and item.

Here is the ambiguity:

<img width="792" alt="screen shot 2016-11-12 at 1 14 55 am" src="https://cloud.githubusercontent.com/assets/2767152/20244108/9f86ab16-a995-11e6-9cb4-ca9da9d9d614.png">

In your source code you have an extension for indexPath and that is conflicting with the apple's extension. As you can see in the screenshot above.

More details can be found on [this question](http://stackoverflow.com/questions/40554840/swift-3-ambigous-use-of-row).

For now i am not using fetch result controller in my project so i just commented out those conflicting properties and my code works fine. I think we have to use some other name for your extensions.

**Comment by CristianCardosoA** [comment]
Just add this lines:

let index = indexPath as NSIndexPath
 let row = index.row

http://stackoverflow.com/questions/40535485/ambigous-use-of-section

**Comment by AgapovOne** [comment]
Why not removing this extension, and using Swift 3 IndexPath `init(row:section:)`?

Then we'll have no conflict for row, but still for sections. Don't know why is this happening. For row that is the solution I think we all need.

**Comment by vmartinelli** [comment]
This issue was resolved by PR #162.
