### ISSUE TITLE
Unable to override `defaultDirectoryURL()`

### ISSUE THREAD

**Issue by mzeeshanid** [Alecrim/AlecrimCoreData#163]
I am just trying to setup my db at custom path i.e to make it available for both my application and its extension. For this i subclassed `GenericPersistentContainer` and override `defaultDirectoryURL` method. But it never called.

If i override it in your internal `NativePersistentContainer` class it get called. So how can i achieve it to make it compatible for both iOS 9 and iOS 10 and setup my db at custom path?

```
class MyPersistentContainer:  GenericPersistentContainer<NSManagedObjectContext> {
    override class func defaultDirectoryURL() -> URL {
        
        debugPrint("defaultDirectoryURL called:")
        
        let url = super.defaultDirectoryURL()
        return url
    }
}
```

**Comment by vmartinelli** [comment]
Hello. I used the above code and the override method is called. Can you confirm if this error persist in your environment?

```swift
class MyPersistentContainer:  GenericPersistentContainer<NSManagedObjectContext> {
    override class func defaultDirectoryURL() -> URL {
        debugPrint("defaultDirectoryURL called:")
        
        let url = super.defaultDirectoryURL()

        return url
    }
}

let persistentContainer: MyPersistentContainer = {
    debugPrint(MyPersistentContainer.defaultDirectoryURL())

    return MyPersistentContainer(name: "ACD_Alarm")
}()
```

**Comment by sobri909** [comment]
I ran into the same problem, and ended up using this workaround: 

```swift
class StalkerPersistentContainer: PersistentContainer {
   
    convenience init() {
        let manager = FileManager.default
 
        let oldUrl = CoreData.oldUrl
        
        if manager.fileExists(atPath: oldUrl.path) {
            log("USING OLD SCHOOL CORE DATA PATH")
            
            CoreData.needsUrlMigration = true
            
            let modelUrl = Bundle.main.url(forResource: "LearnerCoacher", withExtension: "momd")!
            let model = NSManagedObjectModel(contentsOf: modelUrl)!
            
            self.init(name: "LearnerCoacher", managedObjectModel: model, automaticallyLoadPersistentStores: false)

            persistentStoreDescriptions = [NSPersistentStoreDescription(url: oldUrl)]
            
            loadPersistentStores { desc, error in
                if let error = error {
                    log("ERROR: \(error)")
                    return
                }
            }
            
        } else {
            log("USING NEW SCHOOL CORE DATA PATH")
            self.init(name: "LearnerCoacher")
        }
    }
}
```

I haven't tried `defaultDirectoryURL` again yet with the final 5.0 release though.

**Comment by Maxwellimus** [comment]
The issue seems to be with how defaultDirectoryURL is being called by the underlyingPersistentContainers.  The static func in GenericPersistentContainer is never being called when CoreData is being initialized.  The NativePersistentContainer and CustomPersistentContainer always just look at their defaults instead of calling the defaultDirectoryURL() class func in GenericPersistentContainer.

I'm not sure of a good way to solve this since the underlyingPersistentContainers have no idea if you've overriden the class func.  Maybe it should be passed in the init to each of the underlyingPersistentContainers?

**Comment by Maxwellimus** [comment]
Created a pull request with a tested fix here:

https://github.com/Alecrim/AlecrimCoreData/pull/166
