### ISSUE TITLE
which cocapods AlecrimCoreData version to be use for swift 2 in xcode 7 ?

### ISSUE THREAD

**Issue by parthjdabhi** [Alecrim/AlecrimCoreData#164]
which cocapods AlecrimCoreData version to be use for swift 2 in xcode 7 ?

**Comment by vmartinelli** [comment]
Hello. The 4.2.1 (https://github.com/Alecrim/AlecrimCoreData/releases/tag/4.2.1) is the last version with that supports Xcode 7 / Swift 2.2.
