### ISSUE TITLE
AlecrimCoreData 5 Migration Guide ?

### ISSUE THREAD

**Issue by alvinmeimoun** [Alecrim/AlecrimCoreData#167]
Hi,

I tried to update my project using version 4.x to 5.0, but i don't wan't to use persistent container that force me to rewrite a lot of code of my app, i just wan't my DataContext back.

I found a way using PersistentContainer(name: "mycontext").viewContext and changed renamed methods. (I don't found anything for what is the name parameter, i think it's the name in my database model file myname.xcdatamodeld). so when i run my app i got the following error and my app go in a bad exec. So i revert my code waiting resolution of this bug

> CoreData: warning: Unable to load class named ... Class not found, using default NSManagedObject instead.

I think it's just simple thing that i missed when i migrated my project.

So there is any migration guide ? I can stay with version 4.x but i don't wan't to be blocked when Swift 4 will be released and i don't wan't too to rewrite my data access code using raw CoreData methods instead using AlecrimCoreData.

Thanks

**Comment by alvinmeimoun** [comment]
I finally found why i got this error, i removed @objc in the generated CoreDataClass (i generated my entities with the last version of ACD GEN)

So it seems to be an ACD Gen issue

**Comment by m1entus** [comment]
This would be helpful, because i was using DataContext etc. and now it was migrated to PersistentContainer from iOS 10
