### ISSUE TITLE
Updating AlecrimCoreData to Swift 3

### ISSUE THREAD

**Issue by philipborges** [Alecrim/AlecrimCoreData#169]
Hi.

Recently I was asked by a company to go through some code of an app and update it to Swift 3. No worries I thought, I’ve done that for the company before. But the latest code of the app is from 2014 and it uses an old version of AlecrimCoreData. 

The problem is that the app is fairly big and it generates a lot of errors related to the old AlecrimCoreData code. I started by importing the latest ACD framework via cocoapods and that went well. But as far as I can see a lot of changes has happened to the ACD code since 2014. 

My question is: **_what is the best way for me to update the old ACD code to the latest?_**

I looked at the ACD documentation on GitHub, but couldn’t find the needed answers related to updating old ACD code.

Kind regards,
Philip Borges

**Comment by dtartaglia** [comment]
This might help:

Here is (some of) my data model from December 2014:

	import Foundation
	import AlecrimCoreData


	let db = DataModel()


	class DataModel: CoreDataModel {
	
		var attachments: CoreDataTable<AttachmentEntity> {
			return CoreDataTable<AttachmentEntity>(dataModel: self)
		}

		var incidentReports: CoreDataTable<IncidentReportEntity> {
			return CoreDataTable<IncidentReportEntity>(dataModel: self)
		}

		var witnesses: CoreDataTable<WitnessEntity> {
			return CoreDataTable<WitnessEntity>(dataModel: self)
		}

		private convenience init() {
			self.init(modelName: nil)
		}
	}

Here is my most recent data model:

	import AlecrimCoreData
	import CoreData


	let db = PersistentContainer(name: "Marksman").viewContext

	extension NSManagedObjectContext {

		var attachments: Table<AttachmentEntity> {
			return Table<AttachmentEntity>(context: self)
		}

		var incidentReports: Table<IncidentReportEntity> {
			return Table<IncidentReportEntity>(context: self)
		}

		var witnesses: Table<WitnessEntity> {
			return Table<WitnessEntity>(context: self)
		}
	}

In my case, this one file is the only one that imports AlecrimCoreData. Hope it helps...
