### ISSUE TITLE
Any way to extend the library?

### ISSUE THREAD

**Issue by tonglil** [Alecrim/AlecrimCoreData#17]
How can I "extend" the Table class?

I tried:
```swift
import Foundation
import CoreData

extension Table {
    ...
}
```
but it says use of undeclared type 'Table'.  I installed the library by dragging the project into my project.

I want to add a method to overload the `createOrGetFirstEntity` method so that I can pass in multiple attributes.

It would be great if those methods can also accept arrays and/or NSPredicates in addition to strings.

**Comment by vmartinelli** [comment]
If you can, I would welcome your views on the latest versions. Thank you. :-)
