### ISSUE TITLE
firstOrCreated usage

### ISSUE THREAD

**Issue by Firefox2005** [Alecrim/AlecrimCoreData#170]
Hey,

I wanted to use the firstOrCreated method as shown in the Readme:

`let person = context.people.firstOrCreated { $ 0.identifier == 123 }`

But it fails because the usage with the NSComparisonPredicate seems to be totally different from the one documented in the Readme.

I ended up using: 

           if let _ = context.users.first(where: { $0.email == mail }){
                  //do nothing
           } else {
                 let newUser = context.users.create()
                 newUser.email = newValue!
           }

How is firstOrCreated intended to be used now? 
I think it would be helpful to update the Readme.

Thanks for the help, Marc

**Comment by vmartinelli** [comment]
Hello. I could not pay more attention to the repository for some time. Sorry for not answer you before.

The syntax of your code appears to be correct, but the `firstOrCreated` was a convenience method and it worked in very specific ways behind the scenes. It will probably no longer exist in future versions. I suggest you to keep the new code or add constraints to the email attribute.
