### ISSUE TITLE
Xcode 9 Error - Associated type 'Element' references itself

### ISSUE THREAD

**Issue by ckakei** [Alecrim/AlecrimCoreData#172]
While I try to build the app in Xcode 9, it build fail with this error.
<img width="1022" alt="screen shot 2017-08-28 at 4 30 32 pm" src="https://user-images.githubusercontent.com/699736/29765625-8c348fe0-8c0e-11e7-943a-982cb9926b98.png">

**Comment by paweljankowski** [comment]
Can we resolve this issue? It's pretty annoying now...

**Comment by mkelowna** [comment]
You can resolve this issue by deleting the offending line. this is because In Swift 4, the protocol Sequence already defines Element.

`public protocol Sequence {

    /// A type representing the sequence's elements.
    associatedtype Element where Self.Element == Self.Iterator.Element`

**Comment by btelintelo** [comment]
I created a PR.  You can do pod 'AlecrimCoreData', :git => "https://github.com/btelintelo/AlecrimCoreData.git", :branch => 'master' until it gets merged/fixed

**Comment by xremix** [comment]
@btelintelo thank you so much for taking a look at this!
Using your branch I get the following error now:
```
Initializer for conditional binding must have Optional type, not 'NSManagedObjectModel'
```

Do you have any idea on how to fix this?
I get this in the same file in line 107 where it is saying:
```SWIFT
if let model = NSManagedObjectModel(contentsOf: modelURL) {
```

**Comment by btelintelo** [comment]
what version of Alecrim were you using before?  I branched of alecrim master.

**Comment by xremix** [comment]
@btelintelo thanks for your fast reply, I was using the latest version from the master branch before.

**Comment by btelintelo** [comment]
Hi @vmartinelli Do you have any update on if this can get fixed for swift 4?

**Comment by mniksvitla** [comment]
The issue still exists, do you have any update on when it would be fixed?

**Comment by btelintelo** [comment]
pod 'AlecrimCoreData', :git => "https://github.com/btelintelo/AlecrimCoreData.git", :branch => 'swift4-default-directory';
