### ISSUE TITLE
firstOrCreated with multiple conditions

### ISSUE THREAD

**Issue by mrott** [Alecrim/AlecrimCoreData#173]
I'm trying to get or create an object filtering using more conditions:

let person = context.people.firstOrCreated { $ 0.identifier == 123 && $0.name == "name"}. 

it seems that the library is not allowing to do this. Is there any workaround?

Thank you

**Comment by vmartinelli** [comment]
Hello. I could not pay more attention to the repository for some time. Sorry for not answer you before.

The `firstOrCreated` was a convenience method only. And it worked only with one condition. You can try to fetch the entity from context before and if it does not exist, insert one new instance.
