### ISSUE TITLE
Repo owner has gone AWOL

### ISSUE THREAD

**Issue by btelintelo** [Alecrim/AlecrimCoreData#176]
Fix would be owner coming back and helping us merge PR's. 🥇

**Comment by waltermvp** [comment]
@btelintelo i think it's time for the community to agree on a fork. This has been going on since swift 2. What are the most popular forks at the moment?

**Comment by vmartinelli** [comment]
I think this has been going on since before Swift 1. ;) Where are the PRs from the most popular forks at the moment?
