### ISSUE TITLE
Swift 4 error Only classes and class members may be marked with 'final'

### ISSUE THREAD

**Issue by ckakei** [Alecrim/AlecrimCoreData#177]
I am getting this error when I migrated to swift 4.

**Comment by karthikAdaptavant** [comment]
yes i too. or is there any specific branch or tag for swift 4 ?

**Comment by btelintelo** [comment]
pod 'AlecrimCoreData', :git => "https://github.com/btelintelo/AlecrimCoreData.git", :branch => 'swift4-default-directory';
