### ISSUE TITLE
Many to many relationship

### ISSUE THREAD

**Issue by zoli7** [Alecrim/AlecrimCoreData#26]
Can you update the example to provide a many to many relationship? I haven't managed to make it work. In the meantime if I succeed I will make a pull request.

**Comment by brsmith080** [comment]
May not be your problem, but I had to do something different to get a many to many working (and from what I was reading this would apply to a one->many from the one side):

```
func addRelatedItem(value: NSManagedObject, forKey: String) {
  var items = self.mutableSetValueForKey(forKey);
  tems.addObject(value)
}
```
