### ISSUE TITLE
Need for numeric only version/release tags because Carthage does not support version tags with characters

### ISSUE THREAD

**Issue by choiceforyou** [Alecrim/AlecrimCoreData#31]
Following does not work:
github "Alecrim/AlecrimCoreData" == 3.0-beta.1
or
github "Alecrim/AlecrimCoreData" "3.0-beta.1"

Carthage README link which states the above:
https://github.com/Carthage/Carthage/blob/83bbffd25172df767cf578ca17b0cfbbbf913d35/README.md#tag-stable-releases

**Comment by vmartinelli** [comment]
Your are right. I will update the docs in the next beta, replacing "3.0-beta.1" for "2.1" (the last stable release). Thank you.
