### ISSUE TITLE
Not working with newest Xcode update

### ISSUE THREAD

**Issue by MotoxX** [Alecrim/AlecrimCoreData#32]
Hi, unfortunatly I just did the update for Xcode to the newest version and now I can't use your framework anymore as I get many failures now. is there a workaround as I need that to be working by tomorrow? thanks a lot

**Comment by vmartinelli** [comment]
Hello. I had some problems in previous commits. Please verify that if the last pre-relase (3.0-beta.3) is working properly. Thank you.

**Comment by MotoxX** [comment]
It works now. Thank you very much!!!

**Comment by vmartinelli** [comment]
:-)
