### ISSUE TITLE
Problem filtering nested NSManagedObjects

### ISSUE THREAD

**Issue by xmenus** [Alecrim/AlecrimCoreData#34]
Hi,
I'm not being able to filter using .filter(predicateClosure:..) for the example as below:
 Let's assume we have 2 Entities

```swift
class Event: NSManagedObject {

    
    @NSManaged var name: String
    @NSManaged var timeStamp: NSDate
    @NSManaged var place: Place

}

extension Event {
    
    static let name = AlecrimCoreData.Attribute<String>("name")
    static let timeStamp = AlecrimCoreData.Attribute<NSDate>("timeStamp")
    static let place = AlecrimCoreData.Attribute<Place>("place")

}
```

and second Entity

```swift
class Place: NSManagedObject
{

    @NSManaged var name: String
    @NSManaged var event: Event

}


extension Event {
    
    static let name = AlecrimCoreData.Attribute<NSDate>("name")
    static let event = AlecrimCoreData.Attribute<Event>("event")
    
}
```
As you can see there's relation between Event and Place.

I want to filter as follows

```swift
let result = dataContext.places.filter({$0.event.name == "iOS Event"}).toArray()
```

So the problem here is that I'm not being able to access **event name** through 

```swift
$0.event.name
```
Any solution?!

Thanks in advance!

**Comment by vmartinelli** [comment]
Hello.

Currently it is not possible to use the attribute names of related entities in this type of predicate closures. (You can still compare the related entity with `nil` or with other instance of the same type inside the closure, however.)

To obtain the result expected by the code you gave as example, you can use the old-fashioned way:

```swift
let result = dataContext.places.filterBy(predicateFormat: "event.name == %@", arguments: "iOS Event").toArray()
```

I hope to find a way to implement the filter as you exemplified in the future. We are pushing Swift to its limits here. ;-)

Thank you.

**Comment by bettimms** [comment]
I already used your approach! 
Thank you.

**Comment by vmartinelli** [comment]
Good news! If you use the latest beta version (3.0-beta.5) and ACDGen utility to create the code for your entities, you can now write the code just the way you want:

```swift
let result = dataContext.places.filter({$0.event.name == "iOS Event"}).toArray()
```

(At least to a level more, until we have a implementation of expressions trees.)

**Comment by xmenus** [comment]
Glad to hear that! Well done mate!
 Thanks
