### ISSUE TITLE
Carthage Error:  The following build commands failed: 	CompileSwift normal x86_64 /Users

### ISSUE THREAD

**Issue by waltermvp** [Alecrim/AlecrimCoreData#35]
When running `carthage update` I get the following error:
```
The following build commands failed:
	CompileSwift normal x86_64 /Users
```

**Comment by vmartinelli** [comment]
Hello. I reviewed the files of projects and it seemed to go OK, without absolute links. I personally do not use the Carthage. It would be interesting if someone that knows Carthage see this message. Maybe he/she could help best. Let us wait.

**Comment by waltermvp** [comment]
@vmartinelli very very thanks anyways! ill post this on twitte/SO to see if i can get the right person on this.

**Comment by brsmith080** [comment]
seems like this is the root reason for failures: Carthage/Carthage#417. I was able to just remove the 7.1 simulator and things were happy for me.

Probably be good to post the log from building as well though, it'll tell you where it is when you try to "carthage build". You can also "carthage build --no-skip-current" from your project's Carthage/Checkouts/AlecrimCoreData folder to attempt to build only AlecrimCoreData to get a log for only it it building.

**Comment by vmartinelli** [comment]
Carthage support is removed for now. Sorry. Please see #42
