### ISSUE TITLE
SingleEntityAttribute

### ISSUE THREAD

**Issue by bhowell2** [Alecrim/AlecrimCoreData#36]
Having trouble with the ACDGen. I get the error *SingleEntityAttribute<T> does not have a member named init*. Is my compiler not recognizing that it should be using the parent entity's (Attribute) initializer. I see that SingleEntityAttribute is an empty class and it is marked as ACDGen support. Is this expected. Maybe I don't understand the subtleties, but is there a reason for this? (maybe it is for future support?)

*Using swift 1.2 and AlecromCoreData3.0.0-beta5*

This library looks awesome, btw!

**Comment by vmartinelli** [comment]
Hello. This issue was fixed on the "develop" branch. Could you do a test using "develop" branch and see if it works correctly now? Thank you. :-)

**Comment by vmartinelli** [comment]
Update: The fix was incorporated on beta 6 as well.

**Comment by bhowell2** [comment]
The newly generated file: NSManagedObject has a circular reference (it's a subclass of itself) - which won't let it build, but also causes the indexer to go haywire.

I don't have any more time to trace the code right now, but the DataContext() is returning nil. I created the model from the correct datamodel file, but it is not the "standard" data model file that "comes with" the project -- that is to say, if my project is called TheProject. The data model is not: TheProject.xcdatamodeld  . I don't have time to trace the code right now, but I didn't see where it would be possible to specify the datamodel to obtain when creating the DataContext. (i'm guessing it's looking for the project's name datamodeld file?)

So, I can't be sure if the SingleEntityAttribute is working correctly now, but I imagine it is - should have just been that init statement (I think I tried to add this, but maybe I didn't clean my build before rerunning it)

**Comment by vmartinelli** [comment]
Hello. Can you review if the class names for entities are set in model inspector (below entity object name) in the format:  bundleName.entityName (ex: MyApp.customerEntity)?

**Comment by bhowell2** [comment]
They weren't using MyApp.CustomerEntity. They were simply using CustomerEntity. I was then adding @objc() at the top (i can't remember if yours had it already)

**Comment by vmartinelli** [comment]
I'm not sure I understand the problem, but take a look at https://github.com/rnystrom/Swift-CoreData about the entity class namespace.

**Comment by bhowell2** [comment]
Sorry, I haven't done any iOS programming in a few days and haven't gotten back to testing your updated generator. 

I don't know if your generator requires it, but is the MyProjectName.EntityName actually required for core data? I don't seem to be having any problem (with core data, haven't used alecrim yet, again) so long as I add @objc(EntityName):

```
@objc(Tag)
class Tag: NSManagedObject {

    @NSManaged var tag: String

}
```

I can create, save, and retrieve an object.  Am I missing something? I see a lot of articles stating that this (the project name prefixing the class) must be done, but I don't believe i've seen any regarding Swift 1.2. Nor, do I have an issue so long as @objc(EntityName) is added.

**Comment by vmartinelli** [comment]
Well... The `@objc(EntityName)` thing may work in some cases, but I think the `MyModule.MyEntityClass` approach is better because it provides more scalability. The `.xcdatamodeld` file can be in another module (embedded in other framework your app is using, for example).

I'll close this issue, but feel free to comment if you have more questions or new info for sharing.

Thank you. :-)
