### ISSUE TITLE
Problem with distinct()

### ISSUE THREAD

**Issue by bettimms** [Alecrim/AlecrimCoreData#37]
Hi there,

Did you test distinct function?! I doubt if it's working. I'm trying with some records and I'm not seeing it's returning distinct values. 
Here's the usage in 2 ways:

1st:
```swift
var cityAreas:[NSDictionary] = []
//filing somewhere in the code 
cityAreas = dataContext.city.filter({$0.name ==  self.cityName!}).orderBy("area").select({$0.area}).distinct().toArray()
```

2nd: 
```swift
let areas = dataContext.city.filter({$0.name ==  self.cityName!}).select({$0.area}).distinct()
```

**Comment by vmartinelli** [comment]
Hello. You're right. That's why we have beta versions. The attribute query was not taking into consideration other previous parameters before making a new query.

About distinct results the `NSFetchRequest` documentation says: "A Boolean value that indicates whether the fetch request returns only distinct values for the fields specified by propertiesToFetch." For some reason, this is not happening. The problem was solved in another way which is not the best but it might work until a better one is found.

If you can, could you repeat the tests using the latest version of the framework in the "develop" branch?

Thank you very much.

**Comment by bettimms** [comment]
Yes i confirm that now works, but does it worth to include this implementation of distinct() on real projects or no since it seems to be just a temporary solution?!

Thank you

**Comment by bettimms** [comment]
Just for your information, this is my solution of the previous (maybe) stable version, that works fine

```swift
import Foundation
import CoreData

//Mark: BS
extension Table
{
    public func distinctValuesBy(attribute attributeName: String)-> [AnyObject]
    {
        let fetchRequest = self.toFetchRequest()
        fetchRequest.resultType = NSFetchRequestResultType.DictionaryResultType
        fetchRequest.returnsDistinctResults = true
        fetchRequest.propertiesToFetch = [attributeName]
        
        var results = [Dictionary<String, AnyObject>]()
        var distinctValues = [AnyObject]()
        
        var error: NSError? = nil
        if let distinctResult = self.context.managedObjectContext.executeFetchRequest(fetchRequest, error: &error) as? [Dictionary<String, AnyObject>]
        {
            results = distinctResult
            
            for record in distinctResult
            {
                if let value: AnyObject = record[attributeName]
                {
                    distinctValues.append(value)
                }
            }
            
            
        }
        
        return distinctValues
    }
    
    
    
    public func distinctBy(attribute attributeName: String)-> NSArray
    {
        let fetchRequest = self.toFetchRequest()
        fetchRequest.resultType = NSFetchRequestResultType.DictionaryResultType
        fetchRequest.returnsDistinctResults = true
        fetchRequest.propertiesToFetch = [attributeName]

        
        var results = [Dictionary<String, AnyObject>]()
        
        var error: NSError? = nil
        if let distinctResult = self.context.managedObjectContext.executeFetchRequest(fetchRequest, error: &error) as? [Dictionary<String, AnyObject>]
        {
            results = distinctResult
        }
        
        return results
    }
}

```

**Comment by vmartinelli** [comment]
I really liked your code. :-)

Maybe something like this, returning a simple array instead of an array of NSDictionary, can be used in future versions?

About your question, the current implementation appears to be working.

Thank you.
