### ISSUE TITLE
Custom Stack?

### ISSUE THREAD

**Issue by adly-holler** [Alecrim/AlecrimCoreData#41]
Hey, great framework, thanks for sharing it. I'd like to apply it to a project that's also using RestKit. Both frameworks use the same stack – private queue root context, main queue UI context – but both frameworks want to create the stack themselves. 

Is there some way we could add the contexts themselves to `ContextOptions` so that if you want to provide your own, you can?

**Comment by vmartinelli** [comment]
Great idea! Thank you. :-)

I do not have how to test now, but if you have please see `feature/custom_stack` branch. There is a new constructor in `Context`:

```swift
public init?(rootManagedObjectContext: NSManagedObjectContext, mainManagedObjectContext: NSManagedObjectContext)
```

Do you think this way it could work together with RestKit?

**Comment by adly-holler** [comment]
Thanks for the quick response! I'm ready to test but #42 is blocking me

**Comment by vmartinelli** [comment]
Implemented in https://github.com/Alecrim/AlecrimCoreData/commit/eb2c720d8d445287fae7b4a246d652e4f95f64ce
