### ISSUE TITLE
iOS: broken after 3.0-beta-6

### ISSUE THREAD

**Issue by adly-holler** [Alecrim/AlecrimCoreData#42]
If I run `carthage update --platform iOS`, while I'm pointing at any commit after `3.0-beta.6`, Carthage completely skips building `AlecrimCoreData`, since it's specified as a Mac framework. If I build and import the Mac framework into my iOS project, it doesn't export any public symbols – it appears like an empty framework and nothing works.

**Comment by vmartinelli** [comment]
This is sad, but it seems that the Carthage does not support universal frameworks. And it appears that they have no plans to support them. :-(

See: https://github.com/Carthage/Carthage/issues/307

Personally I do not use Carthage, nor my development team. However universal frameworks is one thing we are using, not only in this framework but on several other Alecrim private frameworks.

At the moment I really do not know what answer to give you.

I do not know if it's better to wait what they will do about Carthage.

Here there are no plans to go back and make AlecrimCoreData to use multiple targets as well.

**Comment by adly-holler** [comment]
It's really awful that Alecrim would rather lose Carthage support than make separate targets for separate platforms. =/

**Comment by vmartinelli** [comment]
It depends on the point of view... ;-)

I think it's awful that Carthage loses support for many frameworks that are or will be universal.
