### ISSUE TITLE
FetchedResultsController force refresh

### ISSUE THREAD

**Issue by iCodesign** [Alecrim/AlecrimCoreData#45]
When developing app extensions, I tried to figure out a way to manually refresh `FetchedResultsController` but failed. So I wonder if there should be a method `refresh()` for `FetchedResultsController` or any other solution?

**Comment by vmartinelli** [comment]
Well, I do not know exactly what is the use case, but normally we do this to update the predicates or the sort descriptors. Anyway, take a look at the new methods added to the class in the develop branch. You can now also have access to the underlying fetchRequest. Thank you.

**Comment by iCodesign** [comment]
:clap:
