### ISSUE TITLE
Error in contextOptions var class Context

### ISSUE THREAD

**Issue by adbeelitamar** [Alecrim/AlecrimCoreData#48]
I have everything in place, datamodel, context class, entity class and I still getting this error calling: dataContext.users.createEntity()

![screen shot 2015-05-22 at 1 06 10 pm](https://cloud.githubusercontent.com/assets/2034961/7778760/60896d52-0083-11e5-8f51-5873c3e0a3b3.png)

Do you guys have any clue what could be the problem ?

**Comment by adbeelitamar** [comment]
Nvm, i had a typo on my datamodel file. It was looking the same name as my xcode project

**Comment by brianhu** [comment]
I think the document should mention that the name of the `.xcdatamodeld` file should be the same as the project name.
This stuck me as well.

**Comment by basememara** [comment]
Agreed, same here.

I added a pull request for the change in the docs: https://github.com/ZamzamInc/AlecrimCoreData/commit/8ad34a3ab8e99326acdb18bb07ad4bd561b0e8e7
