### ISSUE TITLE
How to create child context?

### ISSUE THREAD

**Issue by tomaz** [Alecrim/AlecrimCoreData#49]
Previously there was `init(parentContext:)` initializer. It was very convenient to create child contexts that could be easily discarded, but was removed by recent commits. What's the best method to create child contexts on latest code base?

**Comment by vmartinelli** [comment]
Hello. The former `init(parentContext:)` constructor, though convenient, was for private use by AlecrimCoreData. Currently you can create something similar, but in a more complex way. (See `performInBackground` global functions source code for examples.)

Anyway, both the old way and the new way use non-public APIs (from AlecrimCoreData framework, not Apple APIs, it is good to say) and can be changed at any time.

If you are in need of some specific functionality which need something like this, please let me know.

**Comment by vmartinelli** [comment]
I'll close this issue, but if you still have any questions about it, please feel free to reopen it.

**Comment by tomaz** [comment]
Hi!

Thanks for tips and sorry for late reply, had busy couple weeks :)

In the meantime, I added that same convenience initializer as extension. I simply create root+main MOCs, both using parent context, and pass them to base initializer. Gets the job done, but feels overdone.

I think this is common enough operation to warrant convenience initializer out of the box. I'm fine with using my solution though, if you think it's not that important.

In general I find a bunch of interesting stuff that's internal. It simplifies public API, but also adds frustration when there's what seems easy way of achieving something already available but hidden for application (`Stack` class, `contextOptions` property etc)

**Comment by vmartinelli** [comment]
You're right in your observation. It is important, but sometimes it's hard to meet everyone needs and still maintain the simplicity of the library. Anyway, it will be noted for further consideration in future versions. Thank you so. :-)

**Comment by vmartinelli** [comment]
Hi. The next commit on the `develop` branch adds the `createBackgroundContext` global function. I hope this helps in your use case.

**Comment by tomaz** [comment]
Thanks!
