### ISSUE TITLE
How to filter an existing FetchedResultsController?

### ISSUE THREAD

**Issue by basememara** [Alecrim/AlecrimCoreData#50]
Great library, clean and simple API!!

I am following the `MasterViewController` example that is using `FetchedResultsController` which is really nice. I see that it refreshes the `tableview` automatically on creates, updates, and deletes. However, I have a search bar in my navigation. How can I apply a search/filter on the current `FetchedResultsController` instance?

This is the variable I am referring to in `MasterViewController`:
```
    lazy var fetchedResultsController: FetchedResultsController<BlogPostEntity> = {
        let frc = self.dataContext.blogPosts.orderByDescending({ $0.publicationDate }).toFetchedResultsController()
        frc.bindToCollectionView(self.currentCollection)
        return frc
    }()
```

Then in my search button click, what do I do? I can filter the entities like this: `fetchedResultsController.entities.filter`, but this is not using Core Data but searching the entities in place. Or should I overwrite the `fetchedResultsController` variable with a new variable that has the filter like this?:

```
    func searchBarSearchButtonClicked(searchBar: UISearchBar) {
        if !searchBar.text.isEmpty {
            fetchedResultsController = {
                let frc = self.dataContext.blogPosts.filter({ $0.title == searchBar.text }).toFetchedResultsController()
                frc.bindToCollectionView(self.currentCollection)
                return frc
            }()
        }
    }
```

This seems inefficient and problematic. Any proper or built-in way to filter an existing `FetchedResultsController`?

**Comment by vmartinelli** [comment]
Hello. I'm glad you're enjoying the framework. This is an incentive to continue the development. Thank you very much. :-)

About the search, although currently there is no "correct" way to do this, we can use a mix of codes in the conventional manner and the form of AlecrimCoreData as follows:

```swift
func searchBarSearchButtonClicked(searchBar: UISearchBar) {
    if searchBar.text.isEmpty {
        self.frc.fetchRequest.predicate = nil
    }
    else {
        self.frc.fetchRequest.predicate = NSPredicate(format: "title == %@", searchBar.text)
    }
        
    self.frc.refresh()
    self.currentCollection.reloadData()
}
```

I just make a few additions to the framework (`develop` branch) that make this task easier without the mix mentioned above. Also in this case it is not necessary to reload the collection view manually. I would be very happy if you could do some tests and give me feedback if it is working properly. The new form would be:

```swift
func searchBarSearchButtonClicked(searchBar: UISearchBar) {
    if searchBar.text.isEmpty {
        self.frc.resetPredicate()
    }
    else {
        let predicate = self.dataContext.blogPosts.filter({ $0.title == searchBar.text }).predicate
        self.frc.refreshWithPredicate(predicate)
    }
}
```

**Comment by basememara** [comment]
Wow that is really sweet @vmartinelli! The sugar you added in the dev works and feels brilliant!

Just a heads up to anyone, you can do a `pod install` on the dev branch like this:
`pod 'AlecrimCoreData', :git => 'https://github.com/Alecrim/AlecrimCoreData.git', :branch => 'develop'`

Thanks again for making working with Core Data fun and efficient :+1:
