### ISSUE TITLE
Working with one-to-many children properties?

### ISSUE THREAD

**Issue by basememara** [Alecrim/AlecrimCoreData#52]
For one-to-one children properties, it works as expected and I am able to see the properties of the child. However, with one-to-many children properties, it doesn't treat it as a collection of entities so I can't do any filtering of the children (see screenshot below). Is this because of how ACDGen generates the property as a `EntitySetAttribute<Set<SubEvent>>` type?

What I was hoping to do it something like this:
```
dataContext.events.filter {
    return $0.children.any { item in
        item.title.contains("abc")
    }
}
```

I extended the sample to include a one-to-many example to try it out #51. Am I missing something in the framework or syntax?

![capturfiles_114](https://cloud.githubusercontent.com/assets/892152/7922368/b7e8999e-0879-11e5-8c0b-13121d7d53f2.png)

**Comment by basememara** [comment]
I was able to get around it by doing this:

```
dataContext.events.filter {
    return NSPredicate(format: "ANY children.title CONTAINS[cd] %@", searchQuery))
}
```

The `[cd]` is case insensitive btw. Since this worked, I was trying to add this in the API in `class EntitySetAttribute<T>: Attribute<T>` in `Attribute.swift` like this:

`public func any(predicateClosure: (T.Type) -> NSPredicate) -> Bool { ??? }`

The problem is `T.Type` is the not the element but the `Set`. I couldn't figure it out so far so I can do something like this as mentioned:

```
dataContext.events.filter {
    return $0.children.any { item in
        item.title.contains("abc")
    }
}
```

With all the API's and sugar in Alecrim, it's just as powerful that I can still use the native Apple API's for things that aren't covered, nice!

**Comment by vmartinelli** [comment]
Hello. This syntax is a great idea. Thank you. :-)

I've been playing with a way to implement it, but I had no time to create it in a definitive and secure way. As soon as possible I hope to implement it as you exemplified.

Meanwhile, yes: any closure that returns a NSPredicate can return any predicate you want, not necessarily in the AlecrimCoreData format. Your solution was a good one.

**Comment by vmartinelli** [comment]
You were close to the solution. Look at the last commit on the `develop` branch.

**Comment by basememara** [comment]
Awesome it works great! Nice additions of ALL and NONE too. Thanks for opening that door to see how it's done.
