### ISSUE TITLE
Cannot invoke 'orderBy' with an argument list of type '((_) -> _)'

### ISSUE THREAD

**Issue by brianhu** [Alecrim/AlecrimCoreData#55]
I always got this error in swift 1.2 when I did something like `dataContext.people.orderBy({ $0.lastName })` as the tutorial.

Was I doing something wrong?

Thanks!

**Comment by basememara** [comment]
Did you use the ACDGen app to generate your entity classes? It adds attribute properties which enable many parts of AlecrimCoreData that normally aren't available with primitive properties.

**Comment by brianhu** [comment]
I didn't use it. Is ACDGen mandatory to use this syntax?

**Comment by basememara** [comment]
I think so. I tried this in the example app and this worked:
```
dataContext.events.orderBy {
    $0.timeStamp
}
```
But when I removed the extra `Attributes` sugar from `Event.swift`, I couldn't use it anymore. I recommend using ACDGen. It adds a lot of API goodies and is not invasive. It just extends the model classes.

**Comment by basememara** [comment]
Did you get this worked out and can be closed? See #56, you may have forgotten to add "import AlecrimCoreData" at the top to add the extensions.

**Comment by vmartinelli** [comment]
@brianhu: I'll close this issue, but if you have any further questions, please feel free to reopen it.
@basememara: Thank you, again. :-)
