### ISSUE TITLE
Cannot invoke 'firstOrCreated' with an argument list of type '((_) -> _)'

### ISSUE THREAD

**Issue by puelocesar** [Alecrim/AlecrimCoreData#56]
Having this error while trying to use firstOrCreated:

    MasterViewController.swift:21:28: Cannot invoke 'firstOrCreated' with an argument list of type '((_) -> _)'

This is how I'm using it:

    var event = dataContext.events.firstOrCreated({ $0.identifier == 1 })

ps: Just be sure the problem wasn't my setup, I inserted this line on AlecrimCoreDataExample application, and the error persists

**Comment by basememara** [comment]
This is working for me. Be sure to use ACDGen to generate your models. It extends the model classes to use these kinds of syntaxes (see #55).

By the way, there is no `identifier` property on `Event`. I did this and worked:
```
dataContext.events.firstOrCreated {
    $0.timeStamp == NSDate()
}
```

**Comment by puelocesar** [comment]
Ok, I see now that timestamp works, but in my application, I used ACDGen and this is still not working.

code:

     var lugar = dataContext.lugares.firstOrCreated({ $0.site_id == 1 })

ACDGen generated code:

    class Lugar: NSManagedObject {
        @NSManaged var site_id: Int32
    }
    
    extension Lugar {
        static let site_id = AlecrimCoreData.Attribute<Int32?>("site_id")
    }

    class LugarAttribute<T>: AlecrimCoreData.SingleEntityAttribute<T> {

        public override init(_ name: String) { super.init(name) }
        
        lazy var site_id: AlecrimCoreData.Attribute<Int32?> = { AlecrimCoreData.Attribute<Int32?>("\(self.___name).site_id") }()
    }

Same error: 
/Users/paulo/Projetos/Chata de Galocha/Chata de Galocha/SyncManager.swift:107:53: Cannot invoke 'firstOrCreated' with an argument list of type '((_) -> _)'

**Comment by puelocesar** [comment]
Ok, sorry, my fault, I was missing the import AlecrimCoreData on my SyncManager.swift

**Comment by basememara** [comment]
Ahh good catch, this got me one time too - sorry didn't remember this. Thanks for documenting this here for others. Just to note for anyone else, the import is needed to add the extensions.
