### ISSUE TITLE
Pod a BUG

### ISSUE THREAD

**Issue by MakeHui** [Alecrim/AlecrimCoreData#57]
Use in pod for run your AlecrimCoreDataExample Demo, Will appear be a bug
```
fatal error: unexpectedly found nil while unwrapping an Optional value
```

**Comment by basememara** [comment]
Can you give more info on what you are doing exactly to reproduce this error? I'm am using AlecrimCoreData as a pod in another project without an issue. What does the example project have to do with using as a pod?

**Comment by vmartinelli** [comment]
@MakeHui: I'll close this issue, but if you have any further questions, please feel free to reopen it.
@basememara: Thank you. :-)

**Comment by MakeHui** [comment]
@basememara @vmartinelli  oh, I'm sorry, I know the reason! Because before the project is not deleted in the simulator, Produced  cache. Because of my negligence, apologized again. >_<|||

**Comment by andersondborges** [comment]
There is a different configuration to work with pod? I am trying using with pod and I got the same error.
fatal error: unexpectedly found nil while unwrapping an Optional value

I

**Comment by MakeHui** [comment]
@andersondborges  Please try to `iOS Simulator > Reset Content and setting`
