### ISSUE TITLE
Error on ACDGen generated code

### ISSUE THREAD

**Issue by puelocesar** [Alecrim/AlecrimCoreData#58]
Hi, ACDGen generated this code:

```
class Cidade: NSManagedObject {

    @NSManaged var nome: String?

    @NSManaged var pais: Pais?

    @NSManaged var lugares: NSOrderedSet

}

// MARK: - AlecrimCoreData query attributes

extension Cidade {

    static let nome = AlecrimCoreData.Attribute<String?>("nome")

    static let pais = PaisAttribute<Pais?>("pais")

    //error #1
    static let lugares = AlecrimCoreData.EntitySetAttribute<NSOrderedSet>("lugares")

}

class CidadeAttribute<T>: AlecrimCoreData.SingleEntityAttribute<T> {

    public override init(_ name: String) { super.init(name) }

    lazy var nome: AlecrimCoreData.Attribute<String?> = { AlecrimCoreData.Attribute<String?>("\(self.___name).nome") }()

    lazy var pais: PaisAttribute<Pais?> = { PaisAttribute<Pais?>("\(self.___name).pais") }()

    //error #2
    lazy var lugares: AlecrimCoreData.EntitySetAttribute<NSOrderedSet> = { AlecrimCoreData.EntitySetAttribute<NSOrderedSet>("\(self.___name).lugares") }()  

}

```

But the marked lines are failing with the following errors:

/Users/paulo/Projetos/Chata de Galocha/Chata de Galocha/Alecrim/Cidade.swift:33:60: Unexpected trailing closure

/Users/paulo/Projetos/Chata de Galocha/Chata de Galocha/Alecrim/Cidade.swift:45:39: Type 'NSOrderedSet' does not conform to protocol 'CollectionType'

**Comment by puelocesar** [comment]
Changing NSOrderedSet to Set<Lugar> seems to fix the issue

**Comment by vmartinelli** [comment]
Hi. Without an `OrderedSet` type in Swift, ACDGen uses the `NSOrderedSet` in its place. The `CollectionType` issue you mentioned is known. I hope to find (or write) a workaround to this in a future version. Meanwhile could you send me a feedback if replacing it by `Set` causes any collateral effect?

I would to advice that ACDGen currently supports English pluralization only. You may have to make some manual changes so the generated classes can work with the Portuguese entity names too.

**Comment by puelocesar** [comment]
Well, I'm having a problem with using Set, but maybe I'm doing something wrong. Let's say I have a database with a City entity, that has many Places. So, in a UITableViewController, the cities are the section titles and the places are the rows.

So, in cellRowAtIndexPath, if I have NSOrderedSet, I would do something like this:

    var city = getCity(indexPath.section)
    var place = city.places.objectAtIndex(indexPath.row) as Place

And I can't do this with Set<Place>

**Comment by vmartinelli** [comment]
Well. The `indexOf` method of `Set<T>` type may not return what you expect, but I think you can cast it to NSSet without problems:

```swift
let city = getCity(indexPath.section)
let place = (city.places as NSSet).objectAtIndex(indexPath.row) as! Place
```

**Comment by vmartinelli** [comment]
I'll close this issue, but if you have any further questions, please feel free to reopen it.
