### ISSUE TITLE
Error in 'Context' class

### ISSUE THREAD

**Issue by innoreq** [Alecrim/AlecrimCoreData#61]
Hello,

although I'd love to use the framework, I can't because of an error in the 'Context' class:
```
Test Suite 'DBEventTest' started at 2015-06-19 17:38:48 +0000
Test Case '-[HappyFreelancerTests.DBEventTest testACD]' started.
fatal error: unexpectedly found nil while unwrapping an Optional value
```

When looking there, it is obvious why:
```
public class Context {
    
    private let stack: Stack!
    public let managedObjectContext: NSManagedObjectContext!    // the underlying managed object context
    
    private var ___background: Bool = false                     // background context machinery (you did not see it)
    
    internal var contextOptions: ContextOptions { return self.stack.contextOptions }
```
Because 'stack' is nil, the return statement fails when accessing the 'contextOptions' property.

Best regards
Hardy

**Comment by basememara** [comment]
ACD assumes the name of the .xcdatamodeld file should be the same as the project name. This stumped me as well but got past it. See #48.

**Comment by innoreq** [comment]
Well, I created a new CoreData Model, and copied the entities from the old to the new one. Had Xcode create the NSManagedObject class files. Had ACDgen to create the DataContext file. Assigned all of them to both, App and Test Targets. 
Still no change, the error situation continues.

**Comment by basememara** [comment]
Make sure the CoreData Model is the same name as the project. Xcode tends to replace spaces with underscores but that's not gonna work here. Also in your AppDelegate where Xcode puts all the CoreData logic, make sure the SQLite and CoreData models names match the project name as well. Maybe you can upload the project your working on and I can take a look, or take a look at the demo project to match with yours.

**Comment by innoreq** [comment]
Anything to consider in the test target?

**Comment by innoreq** [comment]
All other conditions are fulfilled, actually...

**Comment by magicvoid** [comment]
Add a new Model Version for . xcdatamodeld file can solve this problem.

**Comment by vmartinelli** [comment]
Hello. I'll close this issue, but if you have further questions, please feel free to reopen it or open another one.
