### ISSUE TITLE
How to perform case insensitive sorting?

### ISSUE THREAD

**Issue by tonglil** [Alecrim/AlecrimCoreData#63]
Is there some way to perform caseless sorting?

```swift
        .orderByDescending { (Item) -> Attribute<String> in
            var string = Item.name.___name.lowercaseString
            return Attribute<String>(string) // doesn't seem to apply
        }

        .orderBy {
            $0.name.lowercaseString // does not work, not a string
        }
```

**Comment by vitalyster** [comment]
orderBy("attribute:[cd]")

**Comment by vmartinelli** [comment]
Hi. Currently as @vitalyster said you can use `orderBy("attribute:1:[cd])`, but the `cd` is the third parameter. It is a incomplete implementation anyway. I'll do a commit on `develop` branch that uses the `ContextOptions.stringComparisonPredicateOptions` as the defaults for the sort descriptors too. I think it is not the ideal solution yet, but it is what we have for today. ;-)

**Comment by vmartinelli** [comment]
I had to revert the commit. It will break non string sort descriptors. I'm thinking about a better solution. Meanwhile you can use the solution above.

**Comment by vmartinelli** [comment]
I suspect you've already used, but in 4.0 version there is a static property in `DataContextOptions` just for this. If you have further questions, please feel free to reopen this issue.
