### ISSUE TITLE
Create new main queue child context?

### ISSUE THREAD

**Issue by adly-holler** [Alecrim/AlecrimCoreData#65]
Is there a way to create a new main queue child context of the default main queue context? I want to create an editing screen to contain some pending changes.

Thanks

**Comment by vmartinelli** [comment]
Unfortunately, the current version does not support main queue child contexts, only background queue contexts. A new way to create child contexts (main queue ou background queue) is planned to version 4.0.

**Comment by adly-holler** [comment]
Damn, that's too bad. I'll keep a lookout for 4.0.
