### ISSUE TITLE
Error with batch update: unexpectedly found nil

### ISSUE THREAD

**Issue by basememara** [Alecrim/AlecrimCoreData#66]
I'm trying to use batch update and got this error in `Context.executeBatchUpdateRequestWithEntityDescription` on line `moc.executeRequest(batchUpdateRequest, error: &error) as! NSBatchUpdateResult`: 
```
fatal error: unexpectedly found nil while unwrapping an Optional value
```
I tried the below code in the included sample and resulted in the same issue. I tried debugging it as much as I could, but all the underlying Core Data code looks good regarding `NSBatchUpdateRequest` and `executeRequest`. Any ideas what this could be?
```
    @IBAction func batchUpdate(sender: AnyObject) {
        dataContext.events.batchUpdate({ ($0.timeStamp, NSDate()) }) {
            countOfUpdatedEntities, error in
            if error == nil {
                // ...
            }
        }
        
        dataContext.events.batchUpdate(["timeStamp" : NSDate()]) {
            countOfUpdatedEntities, error in
            if error == nil {
                // ...
            }
        }
    }
```
![capturfiles_137](https://cloud.githubusercontent.com/assets/892152/8785186/f05674ea-2ef3-11e5-80ed-41fcb3c4c43c.png)

**Comment by vmartinelli** [comment]
I was trying to figure out why this is happening, but the `executeRequest::` method keeps returning `nil` without filling the `error`. Take a look at this [link](http://stackoverflow.com/questions/26380458/nsmanagedobjectcontext-executerequest-neither-returns-result-nor-error).

I did some changes, but they do not solve the issue, instead only prevent the "unexpectedly found nil" message. I will continue researching to find out what it is workable solution.

Thank you. :-)

**Comment by basememara** [comment]
This has me stumped for awhile too. I even tried to do a raw batch update request like below but same nil issue:
```
    @IBAction func batchUpdateTapped(sender: AnyObject) {
        let batch = NSBatchUpdateRequest(entityName: "Event")
        batch.propertiesToUpdate = ["timeStamp": NSDate()]
        batch.resultType = .UpdatedObjectsCountResultType
        
        let result = dataContext.managedObjectContext.executeRequest(batch, error: nil) as! NSBatchUpdateResult
        if let numberOfAffectedRecords = result.result as? Int {
            detailDescriptionLabel.text = "Number of records: \(numberOfAffectedRecords)"
        }
    }
```
I found a raw Core Data project where batch update does work. I tried comparing all the code and configurations but I couldn't spot the difference. Here it is: https://www.dropbox.com/s/axyfg3dvqr2sber/Performing%20Batch%20Updates%20on%20Core%20Data.zip?dl=0

**Comment by vmartinelli** [comment]
I think I got it! After many attempts, I found out what in the example is different.

The `executeRequest:` method is only executed on a managed object context without parent context (i.e., the root saving context).

I'll do more tests and then commit the solution.

(Perhaps this deserves to fill a radar with Apple or is it documented somewhere?)

**Comment by basememara** [comment]
Awesome it works! Thx!!

BTW I filled out a Apple bug report #21968677. I'll notify here if I hear anything.
