### ISSUE TITLE
Unit and integration tests

### ISSUE THREAD

**Issue by skyylex** [Alecrim/AlecrimCoreData#70]
I've checked the sources of the framework and didn't find a test target for it. Also I found [the same issue was opened and closed for 2.0](https://github.com/Alecrim/AlecrimCoreData/issues/6).. I didn't find any explanation of reasons.. From my perspective it will logically to improve stability of code and minimize chance of random breaking something, because there a lot of linked functionality in the code. I can help with it. I suggest to use one of the RSpec-like frameworks, either [Quick/Nimble](https://github.com/Quick/Quick) or [Kiwi](https://github.com/kiwi-bdd/Kiwi). They both are very expressive and self-descriptive.

**Comment by vmartinelli** [comment]
Hello. Thank you for bringing this issue to the agenda again.

The tests are part important and I would love that the framework had them and they were very well done.

I have developed the library in my spare time or when I need a feature it in my projects (so I can test that feature in a real situation). Apart from that, I just do not have time to create these tests. And even if he had this time, tests are not my specialty nor they are what I really enjoy to do while programming. In other words, they would not be well done as I like my work to be done.

To create a test project is not enough. There is an architecture and a test plan that should be made. This is not a simple job.

I reopened the #6. If you (and maybe others too) can help with this I would appreciate it very much. :-)

**Comment by skyylex** [comment]
I've started work on some of the tests to find the approach of testing and reveal potential issues. So I created separate branch for this [here](https://github.com/skyylex/AlecrimCoreData/tree/feature/unit-tests). It's not clear when to make a PR, probably we need to discuss the way how it would be. 

Please take a look [here](https://github.com/Alecrim/AlecrimCoreData/issues/72)

**Comment by basememara** [comment]
Thanks @skyylex for the efforts. Would it make sense we apply these efforts on the v4 branch? I know things are very fluid there, but that might be a good thing so we can bake unit testing in from the start and make any changes you need without worrying about affecting production.

**Comment by skyylex** [comment]
@basememara, I see no problem to postpone unit testing to v4. I'm completely agree with @vmartinelli that we need to have complete approach and inject testing as required part of development or decide to reject unit test at all. Partly solutions will bring more pain than profit. So at this moment it makes sense to play with tests at current version to find basic cornerstones. That is what I'm actually doing. As the result of my playing I hope after that I will be able to share some issues which wll help us to find suitable unit-test approach or reject at all the idea of unit tests, as I've already said. 

P.S. I will be grateful for any help on discussing or splitting this preparation work.
