### ISSUE TITLE
Handling duplicates on iCloud - Core Data sync

### ISSUE THREAD

**Issue by bettimms** [Alecrim/AlecrimCoreData#71]
Hi,

What would be best approach to handle duplicates in case on sync of Core Data with iCloud.
After data are coming from iCloud and they are merging with default local data there are duplicates there, so any good approach to handle this please?
Currently I'm doing in the <b>Stack.swift</b> at <b>persistentStoreCoordinatorStoresDidChange</b> but wanted any suggestion for a better approach maybe.

Thanks

**Comment by vmartinelli** [comment]
Hello. I hoped someone else had answered your question

Anyway, to the latest version of Core Data (from Apple, not the **AlecrimCoreData**) there was not a safe way to do this. There are some workarounds, but until today I have not seen one that really be the solution to all cases.

In the last version of Core Data (still in beta) there are constraints for uniqueness, but I have not had chance to test them in practice.
