### ISSUE TITLE
Unit tests and access levels

### ISSUE THREAD

**Issue by skyylex** [Alecrim/AlecrimCoreData#72]
I want to discuss some of the key moments related to tests:

In Swift Unit test bundle we can get access only to public methods due to it's location as independent module. From other side the common approach for software design and it's logically right is to keep in API only necessary staff and as much as possible hide from the user to ease future refactoring and internal changes.

1) So should we test only public API? As a negative side of this is that we skip a lot off functionality in this case. And the whole benefit from test will be lost.
2) If we try to test "internal" methods, how should we call them? I see two options ObjC Swizzling or to put them as compiling sources to the test target.

@vmartinelli and others please share your thoughts on this =)

**Comment by vmartinelli** [comment]
Well, it was a long time before I answer. At this time I was busy on other projects. Please forgive me for the delay.

If you are still excited about writing the tests (which make all of us very happy), I think it is better to write the tests for the Swift 2/Xcode 7, using the built in test library provided instead of any third-party library.

I would like to know your opinion about this, but the opinion of other **AlecrimCoreData** users too.

**Comment by skyylex** [comment]
@vmartinelli, well, let's discuss! =)

So I'm completely agree with your suggestion of Xcode7/Swift 2 usage. Xcode 7 has  "Code coverage" support from the box, and Swift 2 have a lot of useful features.

Acording to the choice of test framework I will try to consider my personal positives/negatives of standard Xcode tests and other third-party variants, if you don't mind. 

I'm very expressed by RSpec concept and will try to explain why I prefer it over xcode test. In standard Xcode test you write prepare methods, then test methods. And it's all about writting methods. Each method tests other method in API. But such approach doesn't show very well what you test. There is no common overview of the test coverage, what test cases were touched. Here comes RSpec with it's tree-like view. It's not about WRITING test anymore it is about DESCRIBING test cases. It's more expresive and understandable for any who wants to fix test or to see what is going on. And from integration perspective it's very comfortable with Swift. Because Swift has simiar concepts.

Another aspect I want to mention is a matchers. Tests mostly is a about comparing some value/state/time with another one. So matchers is a half of all work and it's greatly needed in testing.

The last thing, Xcode test has one significal benefit over all other frameworks. It's official framework and often it means that this tool is more stable. All third party frameworks are built upon the Xcode standard test.

**Comment by vmartinelli** [comment]
@skyylex I trust in your experience about this. Could you provide some (simple) examples? :-)
@basememara What do you think?

**Comment by skyylex** [comment]
@vmartinelli, here the example of Quick/Nimble usage from the developer's documentation:

https://github.com/Quick/Nimble#nimble-expectations-using-expectto
https://github.com/Quick/Quick/blob/swift-2.0/Documentation/QuickExamplesAndGroups.md

Another possible options are [Kiwi](https://github.com/kiwi-bdd/Kiwi) and [Specta/Expecta](https://github.com/specta)
