### ISSUE TITLE
Error : Use of  undeclared typed "MyEntity"

### ISSUE THREAD

**Issue by CsieHoward** [Alecrim/AlecrimCoreData#73]
import AlecrimCoreData
let dataContext = DataContext()

class DataContext: Context {
    var people:      Table<Grade>     { return Table<Grade>(context: self) }
}
___
I follow the tips but soon get in  trouble.
Am i messing up something?
I add  AlecrimCoreData  v3.2 through cocoaPods

**Comment by vmartinelli** [comment]
Hello.

I think that the generic information is missing. You can try:

```swift
import AlecrimCoreData

let dataContext = DataContext()

class DataContext: Context {
    var people: Table<Person> { return Table<PersonEntity>(context: self) }
}
```

Where `Person` is the class that represents the `Person` managed object in your context.

**Comment by CsieHoward** [comment]
I copied the same code and added  entity "Person" in my project.
the Xcode regarded that entity "Person" was not declared.
i m still confused,did i miss some setup steps?

**Comment by CsieHoward** [comment]
<img width="1280" alt="2015-08-12 11 15 57" src="https://cloud.githubusercontent.com/assets/13422175/9215896/87e22cae-40e3-11e5-8f62-8d7376d7a460.png">

**Comment by CsieHoward** [comment]
<img width="1280" alt="2015-08-12 11 16 47" src="https://cloud.githubusercontent.com/assets/13422175/9215902/a49642ae-40e3-11e5-9e71-b73f507ecb70.png">

**Comment by ikesyo** [comment]
It seems that you've define `Person` entity in Core Data's data model, but you don't have the `Person` class which extends `NSManagedObject`. Defining a entity in the data model editor does not mean the corresponding subclass is automatically generated.

**Comment by vmartinelli** [comment]
I think the @ikesyo already answered your question. You can also use [**ACDGen**](https://github.com/Alecrim/ACDGen) to generate the code for your entities if you want. If you have any further questions, please feel free to reopen this issue.
