### ISSUE TITLE
No such module - Xcode 7

### ISSUE THREAD

**Issue by Shogun147** [Alecrim/AlecrimCoreData#74]
Hello,

I installed Alecrim using cocoapods as it's specified in readme:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'AlecrimCoreData', '~> 3.0'
same for just
pod 'AlecrimCoreData'
```

But now when i'm trying to `import AlecrimCoreData`, i'm getting error: `No such module 'AlecrimCoreData'`

Why i'm doing wrong here? Can somebody help with this?

Thanks!

**Comment by vmartinelli** [comment]
Hello. I don't think the last version (3.3.1) will run on Xcode 7. It is a Swift 1.2/Xcode 6 version.

There is a new version on `release/4.0-beta.1` branch that is a WIP for Swift 2/Xcode 7. It is not available via CocoaPods yet, however.
