### ISSUE TITLE
Fix ACDGen or improve diagnostics for ACDGen or provide source code for it

### ISSUE THREAD

**Issue by explicitcall** [Alecrim/AlecrimCoreData#76]
When trying to produce NSManagedObject subclasses with ACDGen it fails without generating anything with inscrutable error with no way to diagnose this.

<img width="482" alt="screenshot 2015-09-06 15 10 01" src="https://cloud.githubusercontent.com/assets/112310/9704759/95c661f8-54a9-11e5-8417-6b49f01b15c5.png">

Please provide source code for ACDGen (as I couldn't find it on GitHub anywhere) so that this error can be diagnosed.

**Comment by vmartinelli** [comment]
The **ACDGen** tool will be open source. As soon as I publish it I'll post the GitHub link here.

**Comment by vmartinelli** [comment]
Done!

You can grab it on: https://github.com/Alecrim/ACDGen.git

:-)

**Comment by explicitcall** [comment]
Thank you, keep up the good work!
