### ISSUE TITLE
Error: `fatal error: unexpectedly found nil while unwrapping an Optional value`

### ISSUE THREAD

**Issue by houmanka** [Alecrim/AlecrimCoreData#78]
Hi. I searched a lot for this issue however I can't find any solution. 

***The same issue is mentioned in another thread, I have done what was suggested however still I got the same issue.***

In `DataContext.swift`
```
let dataContext = DataContext()
class DataContext: Context {
    var profile:      Table<Profile>     { return Table<Profile>(context: self) }
}
```

In the a view controller in `viewDidLoad`
```
 let person = dataContext.profile.createEntity()
 person.email = "h@r.com.au"
 person.first_name = "a_name"
 let (success, error) = dataContext.save()
 if success {
      let count = dataContext.profile.count()
      println(count)
 }
 else {
       println(error)
 }
```

Error:
**`fatal error: unexpectedly found nil while unwrapping an Optional value`**

![screen shot 2015-09-11 at 1 22 45 pm](https://cloud.githubusercontent.com/assets/391493/9806551/51bb3a0e-5889-11e5-82c6-0bbf1bcf2300.png)

I installed module via CocoPods

**Comment by idushes** [comment]
I have same problems

**Comment by vmartinelli** [comment]
Hello. In which line of code you posted the error is happening?

**Comment by idushes** [comment]
in my case 
![screenshot 2015-09-12 01 22 09](https://cloud.githubusercontent.com/assets/13415220/9825446/c6c78704-58ec-11e5-9d0c-d533e3a9ec3a.png)

**Comment by vmartinelli** [comment]
@idushes Can you tell me if the method `assignPersistentStoreCoordinator` from `RootSavingDataContext` class (it is inside the `DataContext.swift` file) is running to the end without errors?

**Comment by vmartinelli** [comment]
I was talking about v4.0-beta.1, sorry. In v3.3.1 the source file is `Context.swift`.

**Comment by idushes** [comment]
yeap
![screenshot 2015-09-12 01 40 43](https://cloud.githubusercontent.com/assets/13415220/9825809/598b1ce8-58ef-11e5-8f71-454d9c27ad71.png)

**Comment by vmartinelli** [comment]
Well... Can you do a test for me? In the line 23 of `Table.swift`, replace its code with the code below:

```swift
let persistentStoreCoordinator = context.parent!.persistentStoreCoordinator!
```

**Comment by idushes** [comment]
![screenshot 2015-09-12 01 46 43](https://cloud.githubusercontent.com/assets/13415220/9825925/30f92274-58f0-11e5-962d-0163dbf4f266.png)

**Comment by vmartinelli** [comment]
I'm away from the computer. I'm sorry. Try:

```swift
let persistentStoreCoordinator = context.parentContext!.persistentStoreCoordinator!
```

**Comment by idushes** [comment]
![screenshot 2015-09-12 01 50 39](https://cloud.githubusercontent.com/assets/13415220/9825996/b2302914-58f0-11e5-99c7-20b6c889ff06.png)

**Comment by bettimms** [comment]
This problem might happen in case your Project name has spaces between words for example `Project Name`.
In order to avoid that set `managedObjectModelName:"Project_Name"` in DataContext configuration.
Also your entities should be updated to be `Project_Name.Profile`.

**Comment by idushes** [comment]
![screenshot 2015-09-12 12 49 43](https://cloud.githubusercontent.com/assets/13415220/9830565/e5e26054-594c-11e5-80ac-cd14ebcbf09d.png)

**Comment by idushes** [comment]
Thank you

**Comment by vmartinelli** [comment]
@bettimms Thank you for the help (again). :)

**Comment by zhihuitang** [comment]
have to say: difficult to use

**Comment by vmartinelli** [comment]
?
