### ISSUE TITLE
ACDGen: Generate with Swift native types instead of their NS equivalents

### ISSUE THREAD

**Issue by csotiriou** [Alecrim/AlecrimCoreData#79]
Hello,

It seems ADGen generates methods and properties based on NSSet, NSString, etc. Is there any way to make it produce Set<> and String equivalents? If not, maybe an option to do so would benefit the developer. Would that make sense?

**Comment by vmartinelli** [comment]
Hello. I think it is just the opposite, this is the default behaviour.

![screen shot 2015-09-13 at 13 32 52](https://cloud.githubusercontent.com/assets/1707194/9837630/28f87d04-5a1c-11e5-9b48-b0b6927a3116.png)

Look at the "Use scalar properties for primitive data types". When this option is marked **ACDGen** uses `String`, `Set` and other Swift types whenever possible.

**Comment by csotiriou** [comment]
Sorry, I guess I missed that part, because I believed that this would just handle Float, Int, etc. Thank you very much for the response.

**Comment by vmartinelli** [comment]
No problem. You are welcome. Thank you for using **AlecrimCoreData**. :-)
