### ISSUE TITLE
Background save in Swift 2.0

### ISSUE THREAD

**Issue by adamszeptycki** [Alecrim/AlecrimCoreData#81]
Hey,
Could any one provide example how to use background save with AlecrimCore data?
I tried to do something like:
```
class MyDataContext: DataContext {
    
    static let dataContext = DataContext()
    
    class func backgroundContext() -> DataContext{
        return DataContext(parentDataContext: MPDataContext.dataContext)
    }
}

let backgroundContext = MyDataContext.backgroundContext()
backgroundContext.performBlock { () -> Void in
//create objects
try backgroundContext.save()
MPDataContext.dataContext.performAndWait({ () -> Void in
    do{
        try MPDataContext.dataContext.save()
    }catch let error{
        completion?(error as NSError)
    }
})

}
```

I don't get any errors but nothing gets saved to .sqlite file (I did checked sqlite file).
Any clues what I doing wrong?

**Comment by vmartinelli** [comment]
Hello. I did a "light" version of your code.

```swift
let backgroundContext = MyDataContext.backgroundContext()

backgroundContext.perform {
    // do some changes
    if let entity = backgroundContext.entities.first() {
        entity.someProperty = someValue
    }

    do {
        try backgroundContext.save()
    }
    catch let error {
        // do error handling error
    }
}
```

About the context not being saved I did not see any changes made in your example code (maybe in your real code that changes are made). Could you check this and post your results?

Thanks.

**Comment by adamszeptycki** [comment]
I was doing changes in line with comment - // create objects.
I don't know why but it started working. @vmartinelli thanks for help and for awesome library :)
