### ISSUE TITLE
Compilation errors after upgrading to ios 9

### ISSUE THREAD

**Issue by guoyu1989** [Alecrim/AlecrimCoreData#82]
Hi, I just upgraded my xcode to version 7 and ios to 9.0, I have many compilation errors pop up, majority of them show in Attribute.swift and look like to be reflection error, can some one help on this, thank you.

**Comment by vmartinelli** [comment]
Hello.

I think you can try this:

1) Close Xcode
2) Delete the files (and folders) inside "~/Library/Developer/Xcode/DerivedData" folder
3) Open Xcode again and reopen the project
4) Menu "Product" -> Clean
5) Menu "Product" -> Build

**Comment by vmartinelli** [comment]
Well... I'll close this issue for now. But if you have further questions, please feel free to reopen it or open another one.
