### ISSUE TITLE
Upgrade project from 3.3.1 version to 4.0

### ISSUE THREAD

**Issue by GalaevAlexey** [Alecrim/AlecrimCoreData#83]
Is It  possible to upgrade my project to swift 2 version of alecrimCoreData using CocoaPods?
Or could you describe how to install alecrimCoreData manually?

**Comment by bettimms** [comment]
There seems to be an error in case of installing AlecrimCoreData 4.0 through CocoaPods, while installing previous version works fine.


<b>[!] Unable to satisfy the following requirements:</b>

- `AlecrimCoreData (~> 4.0)` required by `Podfile`
