### ISSUE TITLE
max for swift 2

### ISSUE THREAD

**Issue by xgdgsc** [Alecrim/AlecrimCoreData#85]
In swift 1.2 I could do:
```
self.table.max({ $0.order })!
```
to get the max value in order column.

How to do the same with swift 2, AlecrimCoreData 4?

**Comment by vmartinelli** [comment]
Hello. Please see the last `develop` branch commit. I would like to ask you to test if the added methods are working properly. Thank you. :-)

**Comment by xgdgsc** [comment]
I get a `Type of expression is ambiguous without more context` error with the calling. Is usage the same as before?

**Comment by vmartinelli** [comment]
Hi. The usage is to be the same. Can you post in which line of the source code this error occurs?

**Comment by xgdgsc** [comment]
```
self.table.max({ $0.order })!
```
code is the same, table is an normal entity, order is an integer attribute. I solved by using another approach that don' t need using max.
