### ISSUE TITLE
Cannot pod install / update to version 4.0

### ISSUE THREAD

**Issue by ckakei** [Alecrim/AlecrimCoreData#86]
[!] Unable to satisfy the following requirements:

- `AlecrimCoreData (~> 4.0)` required by `Podfile`

**Comment by andersondborges** [comment]
You can try 
pod 'AlecrimCoreData', git: 'https://github.com/Alecrim/AlecrimCoreData.git'

**Comment by bettimms** [comment]
Version 4.0 doesnt exist. So go take version number to the release page
https://github.com/Alecrim/AlecrimCoreData/releases
Or easier, install CocoaPodUI plugin for Xcode and just search by name the library/framework you're interested in, it'll find for you latest version of that library (if it's available on pods).
Plugin:
https://github.com/Galeas/CocoaPodUI

**Comment by vmartinelli** [comment]
Well... I personally do not use CocoaPods. I only make **AlecrimCoreData** available via CocoaPods because I know many developers are using it. So... Any help with "pods" is very appreciated. Thank you. :)

**Comment by xrolfex** [comment]
You basically need to push a new pod spec with the updated beta version tag on it.

**Comment by vmartinelli** [comment]
I'm quite busy in another project and I have had little time to respond. Thank for all that answered. :)

Problems with CocoaPods made me anticipate the release of a non-beta release. Improvements and fixes will be implemented anyway, but without using the "beta" version of the name. Please check the last version.
