### ISSUE TITLE
iOS 9 CoreData NSFetchedResultsController update causes blank rows in UICollectionView/UITableView

### ISSUE THREAD

**Issue by queenieapp** [Alecrim/AlecrimCoreData#87]
How to solve this problem?
iOS 9 CoreData NSFetchedResultsController update causes blank rows in UICollectionView/UITableView
https://forums.developer.apple.com/thread/4999

**Comment by vmartinelli** [comment]
Hello. I saw the discussion thread, but I did not have time to check this NSFetchedResultsController issue yet. As soon as I have more information about it, I'll will post a work-around if necessary. Thank you.

**Comment by vmartinelli** [comment]
Any progress with this bug. Does it persist in recente iOS updates?

**Comment by vmartinelli** [comment]
I’ll close this issue for now. If you have further questions, please reopen it.
