### ISSUE TITLE
removeObservers crash

### ISSUE THREAD

**Issue by thellimist** [Alecrim/AlecrimCoreData#88]
Using swift 2

```
import AlecrimCoreData

public class MyContextData {
    public static let sharedInstance = DataContext()
}

extension DataContext {
    var cards:      Table<Card>     { return Table<Card>(dataContext: self) }
}

class Card: NSManagedObject {
    @NSManaged var id: String?
}
```
Calling the code below
```
let card = MyContextData.sharedInstance.users.createEntity()
```
gives crash on ManagedObjectContext Line 323
```
    private func removeObservers() {
        let notificationCenter = NSNotificationCenter.defaultCenter()
        
        for observer in self.observers { // This line crashes
            notificationCenter.removeObserver(observer)
        }
    }
```

**Comment by vmartinelli** [comment]
Hello. Do you have a screenshot of the error occurring while you debug?

**Comment by thellimist** [comment]
Here you go. http://i.imgur.com/Ie3o0BO.png

**Comment by vmartinelli** [comment]
Can you use

```Swift
public let globalInstance = DataContext()
```

As a global variable and see if the errors still occurs?

**Comment by thellimist** [comment]
@vmartinelli the error still occurs

**Comment by xrolfex** [comment]
I had this issue but it was the fact that I had an xcdatamodeld was named differently then my default bundle, after fixing the names to matched I did not have that same issue anymore.

**Comment by thellimist** [comment]
@xrolfex Thanks that was the problem but now I have a different problem. @vmartinelli Using globalInstance.

![image](http://i.imgur.com/PXw1sF5.png)

**Comment by xrolfex** [comment]
This is probably due to in the xcdatamodeld that under configuration section you classes for your entities is not prefixed with the module (aka your bundle name) see example below.
<img width="381" alt="screen shot 2015-10-06 at 7 00 14 pm" src="https://cloud.githubusercontent.com/assets/1327947/10325048/a1d355da-6c5c-11e5-981b-e60038254b32.png">

**Comment by thellimist** [comment]
@xrolfex Thank you that was it.

**Comment by thellimist** [comment]
When changing App Bundle to a name with spaces, I couldn't make the `bundleName.entitiyName` work. I gave the crash on `ManagedObjectContext Line 323` again. @xrolfex do you know how to handle this?

**Comment by xrolfex** [comment]
When you have an App Bundle with spaces such as "Test App" that means your xcdatamodeld would be called "Test App.xcdatamodeld" Inside the configuration part of the xcdatamodeld alecrim changes spaces to underscores. So you would end up having a configuration like below.
<img width="1179" alt="screen shot 2015-10-11 at 9 54 36 pm" src="https://cloud.githubusercontent.com/assets/1327947/10420468/bc6b9c18-7062-11e5-9de6-6a4c4d7eae4a.png">

**Comment by thellimist** [comment]
@xrolfex Thanks again :+1:
