### ISSUE TITLE
NSDate compare in Swift 2.0

### ISSUE THREAD

**Issue by WecanWang** [Alecrim/AlecrimCoreData#89]
Hi , previously I'm compare date in swift 1.2 like the code below and it works fine :

let deleteArray = dataContext.articles.filter { $0.storeDate < dateToCompare}.toArray()

but after I update to 4.0.1beta to test with swift 2.0 it always shows me errors like :

Binary operator '<' cannot be applied to operands of type 'Attribute<NSDate>' and 'NSDate'

Any idea how to slove the problem ? thanks.

**Comment by vmartinelli** [comment]
Hello. The ```storeDate``` managed object field is optional? Or ```dateToCompare``` variable?

**Comment by WecanWang** [comment]
I think both of them were not , if I try to casting storeDate (which type is Attribute<NSDate>) to NSDate like $0.storeDate as! NSDate ,it says it'll always failed. For dateToCompare I've also tried to unwrap it like dateToCompare!  but nothing works,that's all I know ,could these help? Thanks.

**Comment by vmartinelli** [comment]
Can you put this somewhere in your existing code and see if the code compile?

```swift
extension NSDate: Comparable {
}
```

**Comment by WecanWang** [comment]
Sorry for the late reply Vmartinelli  ,looks like after I put the code into my file the errors has gone.Thanks for the help : )

**Comment by vmartinelli** [comment]
You're welcome. :)
