### ISSUE TITLE
Query, filters, etc

### ISSUE THREAD

**Issue by chrux** [Alecrim/AlecrimCoreData#90]
Hi,

Doc and code are not matching but I need help finding out how to filter or use firstOrCreate.

`let predicate = NSPredicate(format: "code = %@", code)
                let transactionType = dataContext.transactionTypes.filterUsingPredicate(predicate).sortByAttributeName("code").first()`

But it's returning nil, even though we have data there.

Best

**Comment by vmartinelli** [comment]
Hello. Can you tell the results of the following code?

```swift
let predicate = NSPredicate(format: "code = %@", code)
let query = dataContext.transactionTypes.filterUsingPredicate(predicate).sortByAttributeName("code")

print(query.predicate)
print(query.sortDescriptors)
```

**Comment by chrux** [comment]
@vmartinelli now it works, I had something bad, now can you ask you for help in how to use these two things, I want to use the properties `sections.count` for a UITableView I have but sections is alway retuning nil.
```let frc = dataContext.transactionTypes.filterUsingPredicate(predicate).sortByAttributeName("text").toFetchRequestController()```

Last, `firstOrCreated` how is it supposed to be used? I dont quite get the 
```dataContext.transactionTypes.firstOrCreated(<#T##predicateClosure: (Self.Item.Type) -> NSComparisonPredicate##(Self.Item.Type) -> NSComparisonPredicate#>)```

Or the 
```dataContext.transactionTypes.first(<#T##predicateClosure: (Self.Item.Type) -> NSPredicate##(Self.Item.Type) -> NSPredicate#>)``` I just need help in this to make the app work again. It's very critical for me

**Comment by vmartinelli** [comment]
Hi. I'm really sorry for the delay in responding.

You can use `firstOrCreated` when you have a field that can identify uniquely the entity you are looking for. If the entity is found, **ACD** brings it for you, else a new one is created and the field you used for search is automatically filled (the other fields you will need to fill yourself, of course).

Example:

```swift
let person = self.dataContext.people.firstOrCreated { $0.someIdentifier == 1000 }
person.name = "John Smith"
try self.dataContext.save()
```

The `first` method, on other hand, only try to find the first occurrence of the entity and can return `nil` if it is not found.

Example:

```swift
var person: PersonEntity! = self.dataContext.people.first { $0.someIdentifier == 1000 }

if person == nil {
    person = self.dataContext.people.createEntity()
    person.someIdentifier = 1000
}

person.name = "John Smith"
try self.dataContext.save()
```

Note that in both cases (that do the same thing) I'm using **ACD** query attributes (the "$0.x" inside the closures). You can generate your entity codes with them using **ACDGen**[https://github.com/Alecrim/ACDGen].

If you do not want to use **ACD** query attributes, you can still return a vanilla `NSPredicate` in the `first` method, but not in the `firstOrCreated` (that is a convenience method, anyway).

I hope this can help you. :)

**Comment by vmartinelli** [comment]
About the fetch request controller, do the code without the 'toFetchRequestController` method return some data?

**Comment by chrux** [comment]
Yes for the last question and for the previous comment, is this working with cocoa pods or I have to submodule the lib and include it in the source of the project
