### ISSUE TITLE
Save data but crashed at try super.save()  

### ISSUE THREAD

**Issue by gizcloud** [Alecrim/AlecrimCoreData#91]
When I try to save data with Swift2.0. The program broke down at , When I ran again, the data has been saved into the database when fetch them. how to solve that?

```
  public override func save() throws {
        guard self.hasChanges else { return }

        try super.save()   <------------- This point

        var error: ErrorType? = nil
        self.rootSavingDataContext.performBlockAndWait {
            self.enableMergeFromRootSavingDataContext = false
            defer { self.enableMergeFromRootSavingDataContext = true }

            do {
                try self.rootSavingDataContext.save()
            }
            catch let innerError {
                error = innerError
            }
        }

        if let error = error {
            throw error
        }
    }
```

My Code is:

```
  @IBAction func doCreate(sender: AnyObject) {

        let dataContext = DataContext();
        let gang = dataContext.gangs.createEntity();
        gang.nick = randomStringWithLength(5);

        gang.nick_py = randomStringWithLength(5);


        do {
           try dataContext.save()
        }
        catch let error {
           print("data saved error \(error)")
        }
}



    }
```

**Comment by vmartinelli** [comment]
Hello. Do you have a description of the `innerError`?

**Comment by gizcloud** [comment]
![Image of Captured Sreen]
(http://i963.photobucket.com/albums/ae117/apprena/captured-screen%202015-10-16%2010.49.50_zpsqhdu5scp.jpg)

**Comment by ssxenon01** [comment]
Hi @gizcloud did you find solution? I'm also getting this error :+1:

**Comment by vmartinelli** [comment]
Without a description of ```innerError``` is very difficult to say something. Can you add...

```swift
print(innerError as NSError)
```

... before the `error = innerError` line inside **ACD** code just for this test?

**Comment by vmartinelli** [comment]
I mean I need to know what is the result of the `print`. The screenshot you made does not have it.

**Comment by ssxenon01** [comment]
There where no error log. Just crash with pointer.
In my case:Error was I initialized DataContext() 2 times in 2 different controller. When i changed it to one. Error was fixed.

**Comment by thellimist** [comment]
I had a similar bug. 
```
let album = dataContext.collectionAlbums.filter({ $0.text ==  text}).first
album.user = user
if album != nil { // Adding this block fixed the bug
  do {
   try dataContext.save()
  }
  catch let error {
   QL4Error("error \(error)")
  }
}


```

**Comment by waltermvp** [comment]
Same issue with me the print never executes

**Comment by waltermvp** [comment]
Update:
Passing around one DataContext object instead of creating them over again solves this issue. Does is make sense to create a singleton function? @vmartinelli

**Comment by amayatsky** [comment]
I have the same issue which is resolved when I use static DataContext

**Comment by vmartinelli** [comment]
Well... Usually only one main thread context is used by an app. Other background contexts can be used as well (temporary or not). Anyway, can you test if this issue occurs using the version from `develop` branch as well?

**Comment by lie-an** [comment]
Hello, I'm having the same error.

I have tested using the version from develop branch as well.

I am saving JSON data (multiple entities) concurrently and the app crash in

`try super.save()`

inside DataContext.swift.

**Comment by amayatsky** [comment]
I had that problem too and ended up using a static instance:
```swift
extension DataContext {
    class var sharedInstance: DataContext {
        struct Static {
            static let instance: DataContext = DataContext()
        }
        return Static.instance
    }
}
```
