### ISSUE TITLE
Crash when try to load momd file 

### ISSUE THREAD

**Issue by said9999** [Alecrim/AlecrimCoreData#95]
<img width="829" alt="screen shot 2015-11-03 at 11 40 21 pm" src="https://cloud.githubusercontent.com/assets/3274722/10912429/6fdd0a06-8284-11e5-95a0-14e701d38a57.png">
not very familiar with core data, pls correct me if I'm wrong...

My code crash at line 149... It seems like if a project named like "A B"(in my case), it's momd file would be "A_B.momd". The space is replaced with an underscore. But in line 149, managedObjectModelName is "A B" which create an invalid url like "A B.momd".

Is there anyway to avoid this problem? Or I have to change my project name without a space?

Thanks.

**Comment by said9999** [comment]
The code is in DataContextOptions.swift. Sorry I forgot to mention this...

**Comment by vmartinelli** [comment]
Hello. White space in names are not supported if the data context options is trying to infer the URLs. You can initialise the options using other initialiser, passing the correct URL as parameter, however.
