### ISSUE TITLE
When is the 4.0.0 official version releasing?

### ISSUE THREAD

**Issue by Lincolnnus** [Alecrim/AlecrimCoreData#97]
The beta package version will get rejected by itunesconnect. May I know when are you going to release the official version? If not so soon, then I may need to abandon the package... <img width="567" alt="not for testing" src="https://cloud.githubusercontent.com/assets/978867/10987574/90d35552-846f-11e5-910c-121c07fd737d.png">

**Comment by ikesyo** [comment]
That is a CocoaPods issue, you should check CocoaPods/CocoaPods#4421 and CocoaPods/CocoaPods#4444.

**Comment by ckakei** [comment]
HELP!!!! 
How to use cocoapod master to fix this bug?

**Comment by vmartinelli** [comment]
Problems with CocoaPods made me anticipate the release of a non-beta release. Improvements and fixes will be implemented anyway, but without using the "beta" version of the name.
