### ISSUE TITLE
Closure Error

### ISSUE THREAD

**Issue by waltermvp** [Alecrim/AlecrimCoreData#98]
when attempting this:

``` swift
if let person = dataContext.people.first({ $0.identifier == 123 }) {
    println(person.name)
}
```

I get the error:
**Type of expression is ambiguous without more context**

It may be a syntax issue since I'm fairly new to swift.

**Comment by waltermvp** [comment]
Red box is where the issue occurs. Also see other classes to make sure its set up correctly. Thanks!
![untitled](https://cloud.githubusercontent.com/assets/1158238/11030113/de0151b8-8699-11e5-981a-aa87edc3c118.png)

**Comment by vmartinelli** [comment]
Hello. The type of `identifier` field is `String?`. Have you tried using quotes?

```swift
if let person = dataContext.people.first({ $0.identifier == "123" }) {
    println(person.name)
}
```

**Comment by waltermvp** [comment]
tried that no luck. Can it be some sort of naming collision for the variable `identifier`?

**Comment by waltermvp** [comment]
same for this 
```swift
        let filteredPeopleCount = dataContext.attendees.count { $0.selected == NSNumber(bool: true) }
```

**Comment by waltermvp** [comment]
let me know if you need any more information, thanks @vmartinelli

**Comment by glebus** [comment]
Hello!

Just faced same issue but with firstOrCreated method.

XCode can't find property "identifier", but model has it. I think it is because in predicateClosure we pass Self.Item.Type.

Here is method declaration:

```swift
public func firstOrCreated(@noescape predicateClosure: (Self.Item.Type) -> NSComparisonPredicate) -> Self.Item
```

And another problem - 

Closure should return NSComparisonPredicate. But in ReadMe.md:

```swift
let person = dataContext.people.firstOrCreated { $ 0.identifier == 123 }
```

$ 0.identifier == 123 returns Bool value. And we get error:

Cannot convert value of type 'Bool' to closure result type 'NSComparisonPredicate'

**Comment by waltermvp** [comment]
@vmartinelli @glebus is ACDGen required for these closures to work?

**Comment by vmartinelli** [comment]
Hello.

Yes, to use this syntax you will need **ACDGen** (or write the generated code, but I think this is not a good idea).

If you do not want to use the code generator you can use the alternative syntax to `firstOrCreated` method:

```swift
let predicate =  NSPredicate(format: "identifier == %@", "123")
var person: PersonEntity! = dataContext.people.filterUsingPredicate(predicate).first()
if person == nil {
    // the person does not exist, create a new one
    person = dataContext.people.createEntity()
    person.identifier = "123"
}

// fill other fields if needed
// ...
```

To sort without **ACDGen** generated code you can also use the methods `sortUsingSortDescriptor` / `sortUsingSortDescriptors`.

**Comment by waltermvp** [comment]
That was my issue. should I submit a pull request to update documentation so that its explicitly says you need 'ACDGen' for specific functions?

**Comment by vmartinelli** [comment]
It will be nice to have this improvement in docs. If you can do this I'll appreciate very much. Thank you. :)

**Comment by waltermvp** [comment]
will do :+1:

**Comment by gfpacheco** [comment]
Are the docs that outdated or am I doing something very wrong?

The docs says you can do this:

    dataContext.people.first({ $0.identifier == 123 })

But the function declaration is this:

    public func first(@noescape predicateClosure: (Self.Item.Type) -> NSPredicate) -> Self.Item?

And of course when I was looking at the docs I got:

    Type of expression is ambiguous without more context

PS: I am using ACDGen

**Comment by waltermvp** [comment]
@gfpacheco thanks for the hint didnt know the type inference worked in `filter`

**Comment by waltermvp** [comment]
@vmartinelli  any update with this I'm still getting the error:
` No '==' candidates produce the expected contextual result type 'NSPredicate'`

for 
`let person = dataContext.patients.firstOrCreated( {$0.patientID == 123})`
